package workspace

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tsukumogami/niwa/internal/agentplan"
)

// These cover the two executor behaviors the composed documents rest on: the
// write-time ownership gate, and the failure message a delivery produces when it
// cannot land. Both are agent-blind -- the executor reads fields off an entry --
// so they are exercised with hand-built entries rather than through a producer.

const testOwnerMarker = "Generated by niwa (test marker)"

// ownedEntry is one whole-file write under the ownership gate.
func ownedEntry(path, content string) agentplan.Entry {
	e := newPlanEntry(agentplan.OpWriteFile, path, content)
	e.Pre = agentplan.IfNotForeign
	e.Owner = testOwnerMarker
	return e
}

func TestApplyPlanOwnershipGate(t *testing.T) {
	t.Run("writes an absent path", func(t *testing.T) {
		target := filepath.Join(t.TempDir(), "doc.md")
		written, _, err := applyPlan(&agentplan.Plan{Entries: []agentplan.Entry{
			ownedEntry(target, testOwnerMarker+"\nfresh\n"),
		}})
		if err != nil {
			t.Fatalf("applyPlan: %v", err)
		}
		if len(written) != 1 {
			t.Fatalf("written = %v, want the one document", written)
		}
	})

	t.Run("refreshes its own prior document", func(t *testing.T) {
		target := filepath.Join(t.TempDir(), "doc.md")
		if err := os.WriteFile(target, []byte(testOwnerMarker+"\nstale\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, _, err := applyPlan(&agentplan.Plan{Entries: []agentplan.Entry{
			ownedEntry(target, testOwnerMarker+"\nfresh\n"),
		}}); err != nil {
			t.Fatalf("applyPlan: %v", err)
		}
		data, err := os.ReadFile(target)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), "fresh") {
			t.Errorf("document was not refreshed: %q", data)
		}
	})

	t.Run("leaves a foreign file alone", func(t *testing.T) {
		target := filepath.Join(t.TempDir(), "doc.md")
		const foreign = "# somebody else's file\n"
		if err := os.WriteFile(target, []byte(foreign), 0o644); err != nil {
			t.Fatal(err)
		}
		written, _, err := applyPlan(&agentplan.Plan{Entries: []agentplan.Entry{
			ownedEntry(target, testOwnerMarker+"\nours\n"),
		}})
		if err != nil {
			t.Fatalf("applyPlan: %v", err)
		}
		if len(written) != 0 {
			t.Errorf("written = %v, want nothing at an occupied path", written)
		}
		data, err := os.ReadFile(target)
		if err != nil {
			t.Fatal(err)
		}
		if string(data) != foreign {
			t.Errorf("the occupied file was modified: %q", data)
		}
	})

	// The gate is what stops a write from following a link out of the tree. A
	// path check before the open would leave a window; refusing the shape is
	// what closes it.
	t.Run("leaves a symlink alone", func(t *testing.T) {
		dir := t.TempDir()
		outside := filepath.Join(dir, "outside.txt")
		if err := os.WriteFile(outside, []byte("untouched\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		target := filepath.Join(dir, "doc.md")
		if err := os.Symlink(outside, target); err != nil {
			t.Skipf("symlinks unavailable: %v", err)
		}

		if _, _, err := applyPlan(&agentplan.Plan{Entries: []agentplan.Entry{
			ownedEntry(target, testOwnerMarker+"\nours\n"),
		}}); err != nil {
			t.Fatalf("applyPlan: %v", err)
		}
		data, err := os.ReadFile(outside)
		if err != nil {
			t.Fatal(err)
		}
		if string(data) != "untouched\n" {
			t.Errorf("the write followed the link: %q", data)
		}
	})

	t.Run("rejects a gate with no owner line", func(t *testing.T) {
		e := newPlanEntry(agentplan.OpWriteFile, filepath.Join(t.TempDir(), "doc.md"), "x")
		e.Pre = agentplan.IfNotForeign
		_, _, err := applyPlan(&agentplan.Plan{Entries: []agentplan.Entry{e}})
		if !errors.Is(err, errMalformedPlanEntry) {
			t.Fatalf("err = %v, want %v: a gate with no owner line answers foreign for every existing file", err, errMalformedPlanEntry)
		}
	})
}

// TestApplyPlanFailureNamesTheCapability is the loud-failure rule. A declaration
// the table calls implemented has to fail with the feature's name in the message
// when its delivery cannot land, rather than as a bare path the user has to
// trace back to a capability themselves.
func TestApplyPlanFailureNamesTheCapability(t *testing.T) {
	dir := t.TempDir()
	blocker := filepath.Join(dir, "blocked")
	if err := os.WriteFile(blocker, []byte("not a directory\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	e := newPlanEntry(agentplan.OpWriteFile, filepath.Join(blocker, "doc.md"), "x")
	e.Capability = agentplan.RepoOrientationDoc

	_, _, err := applyPlan(&agentplan.Plan{Entries: []agentplan.Entry{e}})
	if err == nil {
		t.Fatal("applyPlan succeeded writing under a regular file")
	}
	if !strings.Contains(err.Error(), agentplan.RepoOrientationDoc.String()) {
		t.Errorf("error %q does not name the capability %s it was delivering", err, agentplan.RepoOrientationDoc)
	}
}
