package workspace

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
)

// CodexGenerationMarker is the first line of every Codex context document niwa
// composes inside a repository working tree.
//
// It is a line of the document itself, not a sidecar file and not a filesystem
// attribute: the marker is agent-visible, it counts against the
// `project_doc_max_bytes` budget like any other line, and it leaves the
// never-empty rule unambiguous -- a chain with no content produces no document
// at all, never a marker-only one. The conflict rule (a later issue) recognizes
// niwa's own composed files by this content test rather than by a managed-file
// record, because the standalone `niwa worktree apply` path persists no records
// and must still recognize the override it wrote on the previous run.
//
// It is deliberately not an HTML comment: a reader that strips comments would
// strip the marker, and the marker has to survive whatever reads the file.
// See DESIGN-dual-agent-workspace.md Decision 7 and "The composition rule".
const CodexGenerationMarker = "Generated by niwa (niwa-generated-context): every `niwa apply` rewrites this file, so edits made here are lost."

// CodexComposeRequest is the ordered chain of layers for one Codex-facing
// context document. Zero-valued fields are absent layers.
//
// Codex's context walk delivers only files at or below the nearest project-root
// marker, so no file niwa writes can rely on an outer layer being read
// separately: every composed document carries the full chain from the instance
// root down to its own directory. The field order below is the composition
// order -- outermost first, matching the direction Codex itself concatenates a
// native chain (root first, working directory last), so a session that also
// picks up a committed context file in a subdirectory reads one consistent
// general-to-specific document.
type CodexComposeRequest struct {
	// Instance is the instance-root layer, the outermost one. Present in every
	// composed document.
	Instance string
	// Group is the group-directory layer.
	Group string
	// Repository is the repository layer niwa configures (not the repository's
	// own committed context file, which is CommittedContextPath below).
	Repository string
	// CommittedContextPath, when non-empty, is the path to the repository's own
	// committed context file (today `AGENTS.md`), whose content is inlined after
	// the configured repository layer. `AGENTS.override.md` wins Codex's
	// first-match per-directory precedence, so it displaces the committed file
	// from the discovery slot; inlining is what still gets that content to the
	// session while leaving the committed file untouched.
	//
	// The read is regular-file-only and the enforcement is the open itself --
	// see readRegularFileNoFollow. A path that does not exist is not an error
	// and not a refusal: most repositories commit no context file at all.
	CommittedContextPath string
	// Worktree is the worktree framing layer, appended last. A worktree's
	// document carries the whole chain, not the framing alone.
	Worktree string
}

// CodexInlineRefusal records a committed context file that existed but was not
// inlined, because it was not readable as a regular file. Callers report it
// loudly: the session keeps every workspace layer, and only the repository's
// own content is missing, so the report is the sole signal that anything is.
type CodexInlineRefusal struct {
	// Path is the committed context file that was refused.
	Path string
	// Err is the failure the open or the type check produced.
	Err error
}

func (r CodexInlineRefusal) String() string {
	return fmt.Sprintf("committed context file %s was not inlined (niwa reads it only as a regular file, never through a symlink): %v", r.Path, r.Err)
}

// CodexComposition is the result of composing one Codex context document.
type CodexComposition struct {
	// Content is the composed document: the generation marker on the first
	// line, then every non-empty layer outermost-first, ending in a newline.
	//
	// It is empty exactly when no layer contributed content. Callers MUST then
	// write no file at all -- not an empty one, not a whitespace-only one, not a
	// marker-only one. A file at `AGENTS.override.md` claims the directory's
	// single context slot whatever it holds, so an empty one would suppress the
	// repository's own committed context file entirely and silently. With no
	// file, native discovery delivers that committed file undiminished.
	Content string
	// Refusal is non-nil when a committed context file could not be read as a
	// regular file. The refusal is scoped to the inline and no wider: the
	// workspace layers still compose, and this is what the caller reports.
	Refusal *CodexInlineRefusal
}

// Empty reports whether the composition produced no document, which is the
// caller's signal to write no file.
func (c CodexComposition) Empty() bool { return c.Content == "" }

// ComposeCodexContext builds one Codex-facing context document from an ordered
// chain of layers. It performs no write; the callers that materialize group
// files, per-repository overrides, and worktree files own that.
//
// Two rules carry the safety of this function, and each fails silently if it is
// relaxed:
//
//   - Never empty. A layer whose content is empty or whitespace-only
//     contributes nothing, and a chain that contributes nothing at all yields an
//     empty Content, meaning "write no file".
//   - Regular files only. The committed context file is opened with
//     `O_NOFOLLOW`, so a symlink fails at the open rather than being read
//     through. Composition continues without the inline and the refusal is
//     returned for reporting.
//
// See DESIGN-dual-agent-workspace.md Decision 2A and "The composition rule".
func ComposeCodexContext(req CodexComposeRequest) CodexComposition {
	var result CodexComposition

	// Outermost first. The committed file sits inside the repository layer,
	// after the content niwa configures for the repository and before any
	// worktree framing.
	layers := []string{req.Instance, req.Group, req.Repository}

	if req.CommittedContextPath != "" {
		data, err := readRegularFileNoFollow(req.CommittedContextPath)
		switch {
		case err == nil:
			layers = append(layers, string(data))
		case errors.Is(err, os.ErrNotExist):
			// No committed context file: the ordinary case, not a refusal.
		default:
			result.Refusal = &CodexInlineRefusal{Path: req.CommittedContextPath, Err: err}
		}
	}

	layers = append(layers, req.Worktree)

	var present []string
	for _, layer := range layers {
		// Whitespace-only content counts as no content: it would otherwise
		// produce a document that claims the context slot while saying nothing.
		if strings.TrimSpace(layer) == "" {
			continue
		}
		// Only the trailing newlines are normalized, so the separator between
		// layers is exactly one blank line. The bytes of the layer are otherwise
		// passed through unmodified -- a committed context file is inlined
		// verbatim.
		present = append(present, strings.TrimRight(layer, "\n"))
	}

	if len(present) == 0 {
		// The marker is never written on its own: no content means no file.
		return result
	}

	var b strings.Builder
	b.WriteString(CodexGenerationMarker)
	b.WriteString("\n")
	for _, layer := range present {
		b.WriteString("\n")
		b.WriteString(layer)
		b.WriteString("\n")
	}
	result.Content = b.String()
	return result
}

// HasCodexGenerationMarker reports whether data is a document niwa composed:
// its first line is the generation marker. It is the content half of the
// ownership test the conflict rule applies to an untracked file at one of
// niwa's names (the other half, being untracked, is git state, not content).
func HasCodexGenerationMarker(data []byte) bool {
	firstLine, _, _ := strings.Cut(string(data), "\n")
	return strings.TrimRight(firstLine, "\r") == CodexGenerationMarker
}

// readRegularFileNoFollow reads path only if it is a regular file that is not
// reached through a symlink at its final component, and refuses otherwise.
//
// The refusal is the open, not a check before it. Git reproduces committed
// symlinks verbatim, so a repository can commit its `AGENTS.md` as a symlink to
// any absolute path -- the developer's own agent credentials being the obvious
// target -- and without this rule niwa would read the target and write it into
// the instruction context of every Codex session in that repository. A
// stat-then-open would leave a window between the type check and the read in
// which the path can be swapped; `O_NOFOLLOW` makes the refusal and the read one
// syscall with nothing in between. niwa's claim that it never reads the
// developer's credentials is true only because of this rule.
//
// O_NONBLOCK rides along so a non-regular file cannot stall the apply: opening a
// FIFO for reading otherwise blocks until a writer appears. The type check on
// the already-open descriptor then refuses anything that is not a regular file,
// which is where FIFOs, directories, and devices land.
//
// The guarantee is narrow, deliberately: `O_NOFOLLOW` refuses a symlink at the
// final path component only. Any future read through a longer
// repository-controlled path needs full no-symlink path resolution (an
// `openat2`-style no-symlinks mode), not this.
//
// A path that does not exist returns an error wrapping os.ErrNotExist, which
// the caller distinguishes from a refusal.
func readRegularFileNoFollow(path string) ([]byte, error) {
	if !nofollowSupported {
		return nil, fmt.Errorf("refusing to read %s: this platform cannot refuse a symlink at the open, and no weaker check is accepted here", path)
	}

	f, err := os.OpenFile(path, os.O_RDONLY|nofollowOpenFlags, 0)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return nil, fmt.Errorf("stating %s after open: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("%s is not a regular file (mode %s)", path, info.Mode().Type())
	}

	data, err := io.ReadAll(f)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	return data, nil
}
