package workspace

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/tsukumogami/niwa/internal/agentplan"
)

// The probe is the one place this package looks at content it did not write, so
// its classification is what the whole ownership rule stands on. These cover the
// classification directly, including the tracked branch, which needs no git
// repository because the tracked test is a package variable.

const probeMarker = "Generated by niwa (test marker)"

func probeSpec(dir string) agentplan.ContextProbeSpec {
	return agentplan.ContextProbeSpec{
		Dir:         dir,
		OwnedPath:   filepath.Join(dir, "doc.md"),
		OwnerMarker: probeMarker,
		InlinePath:  filepath.Join(dir, "committed.md"),
	}
}

func TestProbeContextTreeClassifiesTheOwnedPath(t *testing.T) {
	t.Run("absent", func(t *testing.T) {
		got, err := probeContextTree(probeSpec(t.TempDir()))
		if err != nil {
			t.Fatalf("probeContextTree: %v", err)
		}
		if got.Foreign || got.Owned {
			t.Errorf("probe = %+v, want neither foreign nor owned for an absent path", got)
		}
	})

	t.Run("ours", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.WriteFile(filepath.Join(dir, "doc.md"), []byte(probeMarker+"\nbody\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		got, err := probeContextTree(probeSpec(dir))
		if err != nil {
			t.Fatalf("probeContextTree: %v", err)
		}
		if !got.Owned || got.Foreign {
			t.Errorf("probe = %+v, want owned", got)
		}
	})

	t.Run("untracked without the marker is foreign", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.WriteFile(filepath.Join(dir, "doc.md"), []byte("# somebody else's\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		got, err := probeContextTree(probeSpec(dir))
		if err != nil {
			t.Fatalf("probeContextTree: %v", err)
		}
		if !got.Foreign {
			t.Errorf("probe = %+v, want foreign", got)
		}
	})

	// Tracked content is foreign whatever it holds. This is not redundant with
	// the marker test: git-exclude coverage acts only on untracked paths, so a
	// file the repository committed after niwa wrote it would still carry the
	// marker, and only this branch stops the write.
	t.Run("tracked is foreign even with the marker", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.WriteFile(filepath.Join(dir, "doc.md"), []byte(probeMarker+"\nbody\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		prev := pathTrackedByGit
		pathTrackedByGit = func(string, string) bool { return true }
		defer func() { pathTrackedByGit = prev }()

		got, err := probeContextTree(probeSpec(dir))
		if err != nil {
			t.Fatalf("probeContextTree: %v", err)
		}
		if !got.Foreign {
			t.Errorf("probe = %+v, want foreign for tracked content", got)
		}
	})
}

func TestProbeContextTreeReadsTheCommittedFile(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "committed.md"), []byte("# committed\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := probeContextTree(probeSpec(dir))
	if err != nil {
		t.Fatalf("probeContextTree: %v", err)
	}
	if !got.HasInlined || string(got.Inlined) != "# committed\n" {
		t.Errorf("probe = %+v, want the committed file's content", got)
	}
	if got.InlineRefusal != "" {
		t.Errorf("probe refused a plain regular file: %s", got.InlineRefusal)
	}
}

// TestProbeContextTreeRefusesANonRegularCommittedFile covers the shapes the
// inline read will not follow. A symlink is the one that matters: git reproduces
// committed symlinks verbatim, so without the refusal a repository could point
// its context file at anything on the developer's disk and have niwa copy it
// into every session's prompt.
func TestProbeContextTreeRefusesANonRegularCommittedFile(t *testing.T) {
	dir := t.TempDir()
	secret := filepath.Join(t.TempDir(), "credentials")
	if err := os.WriteFile(secret, []byte("token=hunter2\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(secret, filepath.Join(dir, "committed.md")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}

	got, err := probeContextTree(probeSpec(dir))
	if err != nil {
		t.Fatalf("probeContextTree: %v", err)
	}
	if got.HasInlined {
		t.Fatalf("the symlink was read through: %q", got.Inlined)
	}
	if got.InlineRefusal == "" {
		t.Error("the refusal was not reported; it is the only signal the content is missing")
	}
}

// TestProbeContextTreeIsAZeroCostNoOpForAnEmptySpec pins the other half of the
// seam: an agent whose documents are not under an ownership rule pays nothing,
// not even a stat.
func TestProbeContextTreeIsAZeroCostNoOpForAnEmptySpec(t *testing.T) {
	got, err := probeContextTree(agentplan.ContextProbeSpec{})
	if err != nil {
		t.Fatalf("probeContextTree: %v", err)
	}
	if got.OwnedPath != "" || got.Foreign || got.Owned || got.HasInlined || got.InlineRefusal != "" {
		t.Errorf("probe = %+v, want the zero probe", got)
	}
}
