package workspace

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tsukumogami/niwa/internal/config"
	"github.com/tsukumogami/niwa/internal/envformat"
	"github.com/tsukumogami/niwa/internal/github"
	"github.com/tsukumogami/niwa/internal/keyreport"
)

// markedSecret builds the post-resolver shape of a key the resolver could not
// supply: no value, and a mark carrying why.
func markedSecret(cause config.UnresolvedCause, level config.RequirementLevel, desc string) config.MaybeSecret {
	return config.MaybeSecret{Unresolved: &config.Unresolved{
		Cause:        cause,
		Level:        level,
		Description:  desc,
		ProviderKind: "infisical",
	}}
}

// unresolvedEnvCtx builds a materialize context whose effective env holds the
// given values, with no files or discovery involved.
func unresolvedEnvCtx(t *testing.T, values map[string]config.MaybeSecret) (*MaterializeContext, string) {
	t.Helper()
	tmp := t.TempDir()
	repoDir := filepath.Join(tmp, "repo")
	if err := os.MkdirAll(repoDir, 0o755); err != nil {
		t.Fatal(err)
	}
	return &MaterializeContext{
		Effective: EffectiveConfig{
			Env: config.EnvConfig{Secrets: config.EnvVarsTable{Values: values}},
		},
		RepoName:  "myrepo",
		RepoDir:   repoDir,
		ConfigDir: tmp,
	}, repoDir
}

// TestEnvMaterializerOmitsMarkedKeyAndRecordsIt is the headline behaviour: a
// marked key never appears as an assignment, and its record sits at the sorted
// position the assignment would have occupied.
func TestEnvMaterializerOmitsMarkedKeyAndRecordsIt(t *testing.T) {
	ctx, repoDir := unresolvedEnvCtx(t, map[string]config.MaybeSecret{
		"AAA_FIRST":         {Plain: "one"},
		"ANTHROPIC_API_KEY": markedSecret(config.CauseProviderUnreachable, config.LevelRequired, "API key for Claude Code sessions"),
		"ZZZ_LAST":          {Plain: "two"},
	})

	if _, err := (&EnvMaterializer{}).Materialize(ctx); err != nil {
		t.Fatalf("Materialize: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(repoDir, ".local.env"))
	if err != nil {
		t.Fatalf("reading env file: %v", err)
	}
	want := "# Generated by niwa - do not edit manually\n" +
		"AAA_FIRST=one\n" +
		"# niwa: unresolved ANTHROPIC_API_KEY required provider-unreachable \"API key for Claude Code sessions\"\n" +
		"ZZZ_LAST=two\n"
	if string(data) != want {
		t.Errorf("generated file =\n%s\nwant\n%s", data, want)
	}
	if strings.Contains(string(data), "ANTHROPIC_API_KEY=") {
		t.Error("a marked key must never be written with an empty value")
	}
}

// TestEnvMaterializerWritesFileWhenEveryKeyIsUnresolved covers the empty-map
// blocker. A contributor with no vault access resolves nothing at all, and both
// early returns used to leave that repo with no file and therefore no account of
// what was missing.
func TestEnvMaterializerWritesFileWhenEveryKeyIsUnresolved(t *testing.T) {
	ctx, repoDir := unresolvedEnvCtx(t, map[string]config.MaybeSecret{
		"GITHUB_TOKEN": markedSecret(keyreport.CauseNoSource, config.LevelRequired, "GitHub PAT"),
		"OPENAI_KEY":   markedSecret(config.CauseUndeclaredProvider, config.LevelOptional, ""),
	})

	written, err := (&EnvMaterializer{}).Materialize(ctx)
	if err != nil {
		t.Fatalf("Materialize: %v", err)
	}
	if len(written) != 1 {
		t.Fatalf("expected the env file to be written, got %v", written)
	}

	data, err := os.ReadFile(filepath.Join(repoDir, ".local.env"))
	if err != nil {
		t.Fatalf("reading env file: %v", err)
	}
	for _, key := range []string{"GITHUB_TOKEN", "OPENAI_KEY"} {
		if !strings.Contains(string(data), envformat.RecordPrefix+" "+key+" ") {
			t.Errorf("record for %s missing:\n%s", key, data)
		}
		if strings.Contains(string(data), key+"=") {
			t.Errorf("%s written as an assignment:\n%s", key, data)
		}
	}
}

// TestEnvMaterializerRecordsInJSONAndShell: a non-dotenv target gets the record
// in its own format, and the file stays well-formed in that format.
func TestEnvMaterializerRecordsInJSONAndShell(t *testing.T) {
	ctx, repoDir := unresolvedEnvCtx(t, map[string]config.MaybeSecret{
		"REAL":    {Plain: "value"},
		"MISSING": markedSecret(config.CauseKeyNotFound, config.LevelRequired, "needed for CI"),
	})
	ctx.Config = &config.WorkspaceConfig{
		Repos: map[string]config.RepoOverride{
			"myrepo": {EnvOutput: config.OutputTargets{
				{Path: "secrets.local.json"},
				{Path: "env.local.sh"},
			}},
		},
	}

	if _, err := (&EnvMaterializer{}).Materialize(ctx); err != nil {
		t.Fatalf("Materialize: %v", err)
	}

	jsonData, err := os.ReadFile(filepath.Join(repoDir, "secrets.local.json"))
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]string
	if err := json.Unmarshal(jsonData, &doc); err != nil {
		t.Fatalf("json target is not a flat string map: %v\n%s", err, jsonData)
	}
	if doc["REAL"] != "value" {
		t.Errorf("json target lost the resolved key: %v", doc)
	}
	if _, ok := doc["MISSING"]; ok {
		t.Errorf("json target wrote the omitted key as a member: %v", doc)
	}
	if got := doc[envformat.RecordPrefix+" MISSING"]; !strings.Contains(got, "key-not-found") {
		t.Errorf("json record member missing or malformed: %v", doc)
	}

	shData, err := os.ReadFile(filepath.Join(repoDir, "env.local.sh"))
	if err != nil {
		t.Fatal(err)
	}
	for _, line := range strings.Split(strings.TrimSuffix(string(shData), "\n"), "\n") {
		if !strings.HasPrefix(line, "#") && !strings.HasPrefix(line, "export ") {
			t.Errorf("shell target line is neither comment nor export: %q", line)
		}
	}
	if !strings.Contains(string(shData), envformat.RecordPrefix+" MISSING required key-not-found") {
		t.Errorf("shell target missing the record:\n%s", shData)
	}
	if strings.Contains(string(shData), "export MISSING=") {
		t.Errorf("shell target exported the omitted key:\n%s", shData)
	}
}

// TestRecordDoesNotCorruptAdjacentAssignments places a record immediately
// before and immediately after an assignment, and at the first and last lines
// of the file, then reads the file back. Non-corruption is structural — the
// reader drops '#' lines before it splits on '=' — but the property is worth an
// assertion rather than an argument.
func TestRecordDoesNotCorruptAdjacentAssignments(t *testing.T) {
	hostile := "value\nINJECTED=1\n# niwa: unresolved FAKE required no-source \"\""
	record := func(key string) string {
		return string(mustMarshalRecord(t, key, hostile))
	}

	layouts := map[string][]string{
		"record first and last": {
			record("AAA"), "MID=mid", record("ZZZ"),
		},
		"record between two assignments": {
			"BEFORE=b", record("MIDDLE"), "AFTER=a",
		},
		"consecutive records": {
			"BEFORE=b", record("R1"), record("R2"), "AFTER=a",
		},
	}

	for name, lines := range layouts {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), ".local.env")
			body := "# Generated by niwa - do not edit manually\n" + strings.Join(lines, "\n") + "\n"
			if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
				t.Fatal(err)
			}
			vars, records, err := parseEnvFileWithRecords(path)
			if err != nil {
				t.Fatalf("parseEnvFileWithRecords: %v", err)
			}
			for _, line := range lines {
				key, want, isAssignment := strings.Cut(line, "=")
				if !isAssignment || strings.HasPrefix(line, "#") {
					continue
				}
				if got := vars[key]; got != want {
					t.Errorf("%s = %q, want %q", key, got, want)
				}
			}
			if _, ok := vars["INJECTED"]; ok {
				t.Error("a record's description became a real assignment")
			}
			if _, ok := vars["FAKE"]; ok {
				t.Error("a nested record marker became a real assignment")
			}
			if _, ok := records["FAKE"]; ok {
				t.Error("a description's embedded record marker was recovered as a record")
			}
			if len(vars)+len(records) != len(lines) {
				t.Errorf("recovered %d assignments and %d records from %d lines", len(vars), len(records), len(lines))
			}
		})
	}
}

// mustMarshalRecord renders one record line the way the writer does, without
// the header or a trailing newline.
func mustMarshalRecord(t *testing.T, key, desc string) []byte {
	t.Helper()
	data, err := envformat.MarshalItems(envformat.FormatDotenv, []envformat.Item{
		{Key: key, Record: &envformat.Record{Level: "required", Cause: "no-source", Description: desc}},
	})
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimSuffix(string(data), "\n"), "\n")
	return []byte(lines[len(lines)-1])
}

// TestParseEnvFileWrapperPreservesSignature: the existing callers see exactly
// what they saw before, records or not.
func TestParseEnvFileWrapperPreservesSignature(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".local.env")
	body := "# Generated by niwa - do not edit manually\n" +
		"A=1\n" +
		"# niwa: unresolved B required no-source \"why B matters\"\n" +
		"C=3\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	vars, err := parseEnvFile(path)
	if err != nil {
		t.Fatalf("parseEnvFile: %v", err)
	}
	if len(vars) != 2 || vars["A"] != "1" || vars["C"] != "3" {
		t.Errorf("vars = %v, want only the two assignments", vars)
	}

	_, records, err := parseEnvFileWithRecords(path)
	if err != nil {
		t.Fatalf("parseEnvFileWithRecords: %v", err)
	}
	rec, ok := records["B"]
	if !ok {
		t.Fatalf("record for B not recovered: %v", records)
	}
	if rec.Level != "required" || rec.Cause != "no-source" || rec.Description != "why B matters" {
		t.Errorf("record = %+v", rec)
	}
}

// TestParseEnvFileRejectsUntrustedRecords: a repository can write its own
// environment file, so a recovered record is revalidated on the way in.
func TestParseEnvFileRejectsUntrustedRecords(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".local.env")
	body := strings.Join([]string{
		"# niwa: unresolved BAD-KEY required no-source \"\"",
		"# niwa: unresolved OK required no-source unencoded description",
		"# niwa: unresolved OK2 REQUIRED no-source \"\"",
		"# niwa: unresolved GOOD required no-source \"fine\"",
		"REAL=1",
	}, "\n") + "\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	vars, records, err := parseEnvFileWithRecords(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(records) != 1 {
		t.Errorf("records = %v, want only the well-formed one", records)
	}
	if _, ok := records["GOOD"]; !ok {
		t.Errorf("the well-formed record was dropped: %v", records)
	}
	if len(vars) != 1 || vars["REAL"] != "1" {
		t.Errorf("vars = %v", vars)
	}
}

// TestResolvedKeyLeavesNoRecordResidue is R4: a later apply that resolves the
// key removes its record entirely. Generated files are rewritten whole and
// key-sorted on every apply, so this holds by construction — but a regression
// that started appending instead of rewriting would be silent otherwise.
func TestResolvedKeyLeavesNoRecordResidue(t *testing.T) {
	ctx, repoDir := unresolvedEnvCtx(t, map[string]config.MaybeSecret{
		"TOKEN": markedSecret(config.CauseProviderUnreachable, config.LevelRequired, "the token"),
	})
	if _, err := (&EnvMaterializer{}).Materialize(ctx); err != nil {
		t.Fatalf("first Materialize: %v", err)
	}
	envPath := filepath.Join(repoDir, ".local.env")
	first, _ := os.ReadFile(envPath)
	if !strings.Contains(string(first), envformat.RecordPrefix) {
		t.Fatalf("first apply wrote no record:\n%s", first)
	}

	// Second apply: the provider is reachable now.
	ctx.Effective.Env.Secrets.Values["TOKEN"] = config.MaybeSecret{Plain: "resolved"}
	ctx.UnresolvedEnv = nil
	if _, err := (&EnvMaterializer{}).Materialize(ctx); err != nil {
		t.Fatalf("second Materialize: %v", err)
	}
	second, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(second), "niwa: unresolved") {
		t.Errorf("record survived a successful re-resolution:\n%s", second)
	}
	want := "# Generated by niwa - do not edit manually\nTOKEN=resolved\n"
	if string(second) != want {
		t.Errorf("second apply wrote\n%s\nwant\n%s", second, want)
	}
}

// TestLowerLayerPlaceholderIsRemovedByAMark: an unresolved key must not fall
// back to whatever a lower-priority layer happened to seed, which would be a
// quieter version of the confusion omission exists to prevent.
func TestLowerLayerPlaceholderIsRemovedByAMark(t *testing.T) {
	ctx, repoDir := unresolvedEnvCtx(t, map[string]config.MaybeSecret{
		"TOKEN": markedSecret(config.CauseKeyNotFound, config.LevelRequired, ""),
	})
	ctx.EnvExampleVars = map[string]string{"TOKEN": "changeme"}

	if _, err := (&EnvMaterializer{}).Materialize(ctx); err != nil {
		t.Fatalf("Materialize: %v", err)
	}
	data, _ := os.ReadFile(filepath.Join(repoDir, ".local.env"))
	if strings.Contains(string(data), "changeme") {
		t.Errorf("a lower-layer placeholder survived a mark:\n%s", data)
	}
	if !strings.Contains(string(data), envformat.RecordPrefix+" TOKEN ") {
		t.Errorf("no record written:\n%s", data)
	}
}

// TestPromoteThreeWay covers all three arms of the promote branch on the
// instance path: promote a resolved key, omit-and-report a marked one, and keep
// the hard error for a key that is neither — which is what still catches a typo
// in the promote list.
func TestPromoteThreeWay(t *testing.T) {
	t.Run("promotes a resolved key", func(t *testing.T) {
		ctx, _ := unresolvedEnvCtx(t, map[string]config.MaybeSecret{"TOKEN": {Plain: "v"}})
		ctx.Effective.Claude.Env = config.ClaudeEnvConfig{Promote: []string{"TOKEN"}}
		got, _, err := resolveClaudeEnvVars(ctx)
		if err != nil {
			t.Fatalf("resolveClaudeEnvVars: %v", err)
		}
		if got["TOKEN"] != "v" {
			t.Errorf("promoted env = %v", got)
		}
	})

	t.Run("omits and reports a marked key", func(t *testing.T) {
		ctx, _ := unresolvedEnvCtx(t, map[string]config.MaybeSecret{
			"TOKEN": markedSecret(config.CauseProviderUnreachable, config.LevelRequired, "the token"),
		})
		ctx.Effective.Claude.Env = config.ClaudeEnvConfig{Promote: []string{"TOKEN"}}
		keys := keyreport.New()
		ctx.Keys = keys

		got, _, err := resolveClaudeEnvVars(ctx)
		if err != nil {
			t.Fatalf("promotion of an omitted key must not fail: %v", err)
		}
		if _, ok := got["TOKEN"]; ok {
			t.Errorf("omitted key was promoted anyway: %v", got)
		}
		report := keys.Report()
		if len(report) != 1 || report[0].Key != "TOKEN" {
			t.Fatalf("report = %v, want the omitted key", report)
		}
		if report[0].Cause != config.CauseProviderUnreachable || report[0].Level != config.LevelRequired {
			t.Errorf("report entry lost the mark's metadata: %+v", report[0])
		}
	})

	t.Run("errors for a key that is neither", func(t *testing.T) {
		ctx, _ := unresolvedEnvCtx(t, map[string]config.MaybeSecret{"TOKEN": {Plain: "v"}})
		ctx.Effective.Claude.Env = config.ClaudeEnvConfig{Promote: []string{"TYPOD_TOKEN"}}
		if _, _, err := resolveClaudeEnvVars(ctx); err == nil {
			t.Fatal("a promoted key that was never declared must stay a hard error")
		} else if !strings.Contains(err.Error(), "TYPOD_TOKEN") {
			t.Errorf("error = %q, want it to name the key", err)
		}
	})
}

// TestPromoteOmissionIsReportedOnce: the post-merge walk and the promote branch
// see the same shortfall from different angles, and R6 asks for one
// consolidated report rather than one line per producer.
func TestPromoteOmissionIsReportedOnce(t *testing.T) {
	ctx, _ := unresolvedEnvCtx(t, map[string]config.MaybeSecret{
		"TOKEN": markedSecret(config.CauseProviderUnreachable, config.LevelRequired, "the token"),
	})
	ctx.Effective.Claude.Env = config.ClaudeEnvConfig{Promote: []string{"TOKEN"}}
	keys := keyreport.New()
	keys.Add(keyreport.Entry{Scope: "repos.app.env.secrets", Key: "TOKEN", Cause: config.CauseProviderUnreachable})
	ctx.Keys = keys

	if _, _, err := resolveClaudeEnvVars(ctx); err != nil {
		t.Fatalf("resolveClaudeEnvVars: %v", err)
	}
	if report := keys.Report(); len(report) != 1 {
		t.Errorf("report holds %d entries, want one consolidated line: %v", len(report), report)
	}
}

// TestPromoteWorktreePathUsesRecoveredRecords: the worktree path holds no marks
// — it reads an already-materialized file rather than re-resolving — so its
// unresolved set has to come from the records in that file.
func TestPromoteWorktreePathUsesRecoveredRecords(t *testing.T) {
	ctx, _ := unresolvedEnvCtx(t, nil)
	ctx.Effective.Claude.Env = config.ClaudeEnvConfig{Promote: []string{"TOKEN"}}
	ctx.InheritedEnv = map[string]string{"OTHER": "x"}
	ctx.InheritedUnresolved = map[string]unresolvedEnvKey{
		"TOKEN": {Record: envformat.Record{Level: "required", Cause: "provider-unreachable", Description: "the token"}},
	}

	got, _, err := resolveClaudeEnvVars(ctx)
	if err != nil {
		t.Fatalf("worktree promotion of an omitted key must not fail: %v", err)
	}
	if _, ok := got["TOKEN"]; ok {
		t.Errorf("omitted key was promoted: %v", got)
	}

	// A key in neither the inherited env nor the recovered records is still a
	// hard error, so inheritance cannot mask a genuine misconfiguration.
	ctx.Effective.Claude.Env = config.ClaudeEnvConfig{Promote: []string{"ABSENT"}}
	if _, _, err := resolveClaudeEnvVars(ctx); err == nil {
		t.Fatal("expected the promote error for a key absent from config, clone env, and records")
	}
}

// TestReadCloneEnvOutputRecoversRecords wires the reader to the file the
// instance apply actually writes, which is the seam the worktree half depends
// on.
func TestReadCloneEnvOutputRecoversRecords(t *testing.T) {
	cloneDir := t.TempDir()
	body := "# Generated by niwa - do not edit manually\n" +
		"# niwa: unresolved GH_TOKEN required provider-unreachable \"GitHub PAT\"\n" +
		"OTHER=x\n"
	if err := os.WriteFile(filepath.Join(cloneDir, ".local.env"), []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	env, unresolved, err := readCloneEnvOutput(cloneDir, &config.WorkspaceConfig{}, "app", nil)
	if err != nil {
		t.Fatalf("readCloneEnvOutput: %v", err)
	}
	if env["OTHER"] != "x" || len(env) != 1 {
		t.Errorf("env = %v", env)
	}
	got, ok := unresolved["GH_TOKEN"]
	if !ok {
		t.Fatalf("record not recovered: %v", unresolved)
	}
	if got.Record.Cause != "provider-unreachable" || got.Record.Description != "GitHub PAT" {
		t.Errorf("recovered record = %+v", got)
	}
}

// TestClaudeEnvVarsOmitsMarkedValues: the settings document is an environment
// surface too, and an empty ANTHROPIC_API_KEY there is exactly the "configured
// empty" a downstream consumer cannot tell from an unconfigured one. It carries
// no record: settings.local.json is a Claude Code file, not a niwa one.
func TestClaudeEnvVarsOmitsMarkedValues(t *testing.T) {
	ctx, _ := unresolvedEnvCtx(t, nil)
	ctx.Effective.Claude.Env = config.ClaudeEnvConfig{
		Vars: config.EnvVarsTable{Values: map[string]config.MaybeSecret{
			"KEPT":    {Plain: "v"},
			"OMITTED": markedSecret(config.CauseClientNotInstalled, config.LevelRecommended, ""),
		}},
	}
	got, _, err := resolveClaudeEnvVars(ctx)
	if err != nil {
		t.Fatalf("resolveClaudeEnvVars: %v", err)
	}
	if got["KEPT"] != "v" {
		t.Errorf("resolved key lost: %v", got)
	}
	if _, ok := got["OMITTED"]; ok {
		t.Errorf("marked key reached the settings env block: %v", got)
	}
}

// TestApplyWritesRecordForEveryUnresolvedKey is the whole chain against a real
// apply, in the shape this work exists to serve: every declared key comes back
// unresolved, so the value map is empty — and the generated file must still
// exist and account for each key rather than being skipped entirely.
//
// The provider here is reachable and simply holds nothing, because that is the
// shortfall the test fixtures can produce; the materializer treats every mark
// the same way regardless of its cause.
func TestApplyWritesRecordForEveryUnresolvedKey(t *testing.T) {
	withFakeVaultBackend(t)

	configTOML := `
[workspace]
name = "no-provider-ws"

[[sources]]
org = "testorg"

[groups.default]
repos = ["app"]

[vault.provider]
kind = "fake"

[env.secrets]
ANTHROPIC_API_KEY = "vault://ANTHROPIC_API_KEY"
TAVILY_API_KEY = "vault://TAVILY_API_KEY"

[env.secrets.recommended]
ANTHROPIC_API_KEY = "API key for Claude Code sessions"
`

	tmpDir := t.TempDir()
	niwaDir := filepath.Join(tmpDir, ".niwa")
	if err := os.MkdirAll(niwaDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(niwaDir, "workspace.toml"), []byte(configTOML), 0o644); err != nil {
		t.Fatal(err)
	}

	parsed, err := config.Load(filepath.Join(niwaDir, "workspace.toml"))
	if err != nil {
		t.Fatalf("config.Load: %v", err)
	}

	mockClient := &mockGitHubClient{
		repos: map[string][]github.Repo{
			"testorg": {{Name: "app", SSHURL: "git@github.com:testorg/app.git"}},
		},
	}
	groupDir := filepath.Join(tmpDir, "no-provider-ws", "default")
	if err := os.MkdirAll(filepath.Join(groupDir, "app", ".git"), 0o755); err != nil {
		t.Fatal(err)
	}

	applier := NewApplier(mockClient)
	applier.Cloner = &Cloner{}
	if _, err := applier.Create(context.Background(), parsed.Config, niwaDir, tmpDir, parsed.Config.Workspace.Name); err != nil {
		t.Fatalf("apply must survive a host with no vault backend, got: %v", err)
	}

	envPath := filepath.Join(groupDir, "app", ".local.env")
	data, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("a repo whose keys are all unresolved must still get a file: %v", err)
	}
	want := "# Generated by niwa - do not edit manually\n" +
		"# niwa: unresolved ANTHROPIC_API_KEY recommended key-not-found \"API key for Claude Code sessions\"\n" +
		"# niwa: unresolved TAVILY_API_KEY unspecified key-not-found \"\"\n"
	if string(data) != want {
		t.Errorf("generated file =\n%s\nwant\n%s", data, want)
	}

	// Reading the file back yields no assignments at all: a record is a
	// whole-line comment, so nothing here can be mistaken for a value.
	vars, records, err := parseEnvFileWithRecords(envPath)
	if err != nil {
		t.Fatal(err)
	}
	if len(vars) != 0 {
		t.Errorf("records produced assignments on read-back: %v", vars)
	}
	if len(records) != 2 {
		t.Errorf("recovered %d records, want 2: %v", len(records), records)
	}
}
