package agentplan

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/tsukumogami/niwa/internal/agent"
)

// This file holds the per-agent variation in how a context document is built,
// and the probe seam that variation needs. It is a map keyed by agent.Agent
// rather than a pair of per-agent files, matching the only idiom the repo has
// for per-agent behavior, and it lives here rather than in internal/workspace
// because everything in it is a fact about one agent's discovery rules.
//
// The rules encoded below are measured, not inferred (see
// docs/spikes/SPIKE-codex-discovery-mechanics.md):
//
//   - Codex finds a project root by walking up to the nearest directory holding
//     a project-root marker (`.git` by default) and then reads context from that
//     root down to the working directory. It never looks above the root, so a
//     document written at an instance root or a group directory is never visited
//     from a session inside a repository. Workspace and group orientation
//     therefore has to be composed into each repository's own document, which is
//     the only placement a session sees.
//   - Each directory contributes at most one file, chosen by a hardcoded
//     precedence with AGENTS.override.md first. An empty file still claims the
//     slot and suppresses everything behind it, which is why a chain that
//     composes to nothing must produce no file at all rather than an empty one.
//   - The byte budget is one counter spent across the whole chain,
//     outermost-first, and truncation is a raw cut with nothing on stderr. So
//     the chain is measured as it is composed, and the size travels out on the
//     plan to the project-layer configuration that declares a budget covering
//     it.

// codexDocBudget is the default `project_doc_max_bytes` in codex-cli 0.147.0:
// the number of bytes a session spends across the whole composed chain before
// it starts cutting, silently. It is both the value a chain is measured against
// and the floor of anything niwa declares -- see codexBudgetFor.
const codexDocBudget = 32768

// codexBudgetHeadroom is how many times the composed chain the declared budget
// covers. An exact-fit declaration passes an "it all fits" check today and
// starts cutting the innermost layer the moment any file in the chain grows by
// a byte, and the thing being cut is the repository's own content with nothing
// anywhere saying so.
const codexBudgetHeadroom = 2

// codexBudgetFor sizes the `project_doc_max_bytes` niwa declares for a tree
// whose composed chain occupies chain bytes, and returns zero for a chain niwa
// declares nothing for.
//
// Zero is the answer whenever the chain and its headroom still fit the agent's
// own default, which is the ordinary case. Writing the key there would restate
// a default to no effect -- and worse, a project layer outranks the developer's
// own configuration, so a workspace whose chain is a few kilobytes would quietly
// pull a developer who raised their budget back down to whatever niwa picked.
// Lowering a budget somebody chose is not niwa's business; raising one its own
// composition overflowed is.
//
// Past that point the declared value is the chain times the headroom, rounded
// up to a whole multiple of the default. The rounding is what keeps the number
// from tracking the chain byte for byte: without it, editing a line of a context
// file would rewrite the generated configuration with a slightly different
// integer on every apply.
func codexBudgetFor(chain int) int {
	if chain <= 0 {
		return 0
	}
	want := chain * codexBudgetHeadroom
	if want <= codexDocBudget {
		return 0
	}
	if rem := want % codexDocBudget; rem != 0 {
		want += codexDocBudget - rem
	}
	return want
}

// generationMarker is the first line of every context document niwa composes
// into a working tree it does not own.
//
// It is a line of the document rather than a sidecar file or a filesystem
// attribute, because the ownership question is asked in places where no
// managed-file record exists: `niwa worktree apply` persists none, and a
// record-based test would leave that path unable to recognize the document it
// wrote on its own previous run. It is deliberately not an HTML comment -- a
// reader that strips comments would strip the marker, and the marker has to
// survive whatever reads the file. It counts against the byte budget like any
// other line, which is the honest accounting.
const generationMarker = "Generated by niwa (niwa-generated-context): every `niwa apply` rewrites this file, so edits made here are lost."

// composition is how one agent's per-tree context documents are built. The zero
// value is the plain behavior: one document per directory, written whole, with
// no ownership test and no composition -- which is what Claude has always had,
// because a Claude session reads the documents niwa writes above a repository
// where they are written.
type composition struct {
	// owned marks the documents with generationMarker and puts them under the
	// ownership rule: niwa writes only where the name is free or already
	// carries its marker, and never writes a document that composes to nothing.
	owned bool

	// composesOuterLayers folds the workspace and group orientation layers into
	// each repository's own document, for an agent whose discovery never reaches
	// the directories those layers are written in.
	composesOuterLayers bool

	// inlinesCommitted names the repository's own committed context file, whose
	// content is read and inlined after the layers niwa configures. It is set
	// for an agent whose document displaces the committed one from the
	// directory's single context slot; inlining is what still gets that content
	// to the session while leaving the committed file untouched.
	inlinesCommitted string

	// measuresChain marks an agent whose composed chain is spent against a byte
	// budget, so the plan carries the chain's size out to the producer that
	// declares a budget covering it. It is false for an agent that reads its
	// context documents whole.
	measuresChain bool
}

// compositions is the per-agent table. A pair the map does not answer for gets
// the zero composition, which is the fail-safe direction: an agent nobody has
// described yet is prepared the way Claude is rather than having a marker and
// an ownership rule invented for it.
var compositions = map[agent.Agent]composition{
	agent.AgentClaude: {},
	agent.AgentCodex: {
		owned:               true,
		composesOuterLayers: true,
		inlinesCommitted:    "AGENTS.md",
		measuresChain:       true,
	},
}

// composition returns this producer's agent's rules.
func (p Producer) composition() composition {
	resolved, err := agent.ParseAgent(string(p.ag))
	if err != nil {
		return composition{}
	}
	return compositions[resolved]
}

// ContextProbeSpec says what internal/workspace must inspect in one directory
// before this agent's context plan for it can be produced.
//
// It is the leaf's half of the probe seam: reading foreign content in a
// developer's tree and shelling out to git are workspace jobs, and keeping them
// there is what lets the layout scan assert this package neither writes nor
// executes without a list of exceptions. The producer says which paths matter
// and what makes one of them niwa's own; the workspace looks, and hands back a
// ContextProbe.
//
// A zero spec means the agent needs no probe for that directory.
type ContextProbeSpec struct {
	// Dir is the directory the probe is about.
	Dir string

	// OwnedPath is the document whose ownership decides whether niwa may write
	// there at all. Empty when the agent's documents are not under an ownership
	// rule.
	OwnedPath string

	// OwnerMarker is the first line that identifies OwnedPath as niwa's own.
	OwnerMarker string

	// InlinePath is the file the directory may already commit at the slot this
	// agent's document takes, to be read under the regular-file-only rule and
	// inlined. Empty when the agent's document displaces nothing.
	InlinePath string
}

// ContextProbe is what internal/workspace found for one directory.
//
// Foreign and Owned are both false when the path is simply absent, which is the
// ordinary first-apply case.
type ContextProbe struct {
	// Dir is the directory this result is about.
	Dir string

	// OwnedPath is the path that was inspected, carried back so a refusal can
	// name it and the plan can exempt it.
	OwnedPath string

	// Foreign reports that something niwa did not write occupies OwnedPath: a
	// file the repository tracks, a symlink, a directory, or an untracked file
	// without niwa's marker on its first line.
	Foreign bool

	// Owned reports that niwa's own prior document is at OwnedPath, so a
	// re-apply may refresh it in place.
	Owned bool

	// Inlined is the committed file's content, valid only when HasInlined is
	// set.
	Inlined    []byte
	HasInlined bool

	// InlineRefusal describes a committed file that existed and was not read,
	// because it was not readable as a regular file. It is reported only when a
	// document is actually written, since it is the sole signal that the
	// repository's own content is missing from one.
	InlineRefusal string
}

// ContextProbeSpec returns what the caller must inspect in dir before asking
// for a context plan that writes there. The zero spec means nothing.
func (p Producer) ContextProbeSpec(dir string) ContextProbeSpec {
	comp := p.composition()
	if !comp.owned {
		return ContextProbeSpec{}
	}
	spec := ContextProbeSpec{
		Dir:         dir,
		OwnedPath:   p.localContextPath(dir),
		OwnerMarker: generationMarker,
	}
	if comp.inlinesCommitted != "" {
		spec.InlinePath = filepath.Join(dir, comp.inlinesCommitted)
	}
	return spec
}

// composeDocument builds one owned document from an ordered chain of layers:
// the generation marker on the first line, then every layer that carries
// content, outermost first, each separated by a blank line.
//
// It returns nil when no layer contributed. That is the never-empty rule, and
// it is not a tidiness preference: a file at the name this document takes claims
// the directory's single context slot whatever it holds, so an empty one would
// suppress the repository's own committed file entirely and without a word. With
// no file, native discovery delivers that committed file undiminished. The
// marker is never written on its own for the same reason.
//
// Only trailing newlines are normalized, so a layer's bytes are otherwise passed
// through unmodified and a committed context file is inlined verbatim.
func composeDocument(layers ...[]byte) []byte {
	joined := joinLayers(layers...)
	if joined == nil {
		return nil
	}
	return []byte(generationMarker + "\n\n" + string(joined))
}

// joinLayers is composeDocument without the ownership marker: every layer that
// carries content, outermost first, separated by a blank line and closed by a
// newline, and nil when no layer contributed.
//
// It is separate because the marker belongs to the ownership rule rather than to
// composition. A directory niwa owns outright -- the workspace root, an instance
// root -- has no ownership rule to answer to and no committed file to displace,
// so a document composed for one carries the layers and nothing else. A
// directory niwa shares with a repository has both, and composeDocument adds the
// marker that makes the next apply able to recognize its own work.
func joinLayers(layers ...[]byte) []byte {
	var present []string
	for _, layer := range layers {
		if strings.TrimSpace(string(layer)) == "" {
			continue
		}
		present = append(present, strings.TrimRight(string(layer), "\n"))
	}
	if len(present) == 0 {
		return nil
	}

	return []byte(strings.Join(present, "\n\n") + "\n")
}

// conflictWarning is the line reported for one path niwa refused to write.
// Every refusal names its path: a quiet skip is exactly the silent failure the
// ownership rule exists to prevent, and the user has no other way to learn that
// the repository's own file is now the only context a session there gets.
func conflictWarning(path string) string {
	return fmt.Sprintf("%s is occupied by something niwa did not write, so no context document was composed there; nothing at that path was modified or removed, and the session falls back to the repository's own content", path)
}
