package agentplan

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/tsukumogami/niwa/internal/agent"
)

// This file is the producer side of the MCP servers a session can reach. The
// workspace declares each server once, in agent-neutral terms
// (config.MCPConfig), and this file turns that declaration into whichever
// format the agent it produces for actually reads: Claude Code's .mcp.json, or
// Codex's [mcp_servers.<name>] entries in a project-layer configuration.
//
// Four measured properties of codex-cli 0.147.0 govern the generator, and each
// one is mechanized below rather than left to care:
//
//  1. One malformed entry fails the whole config load, taking every valid
//     sibling with it. So the document is validated -- and re-decoded whole --
//     before any of it is declared as a write, and a failure produces an error
//     and no entry at all rather than a file that bricks a session.
//  2. A name collision merges recursively, field by field, instead of
//     overriding: niwa's command running with the developer's args and cwd is a
//     server neither party wrote. So a collision with a name the developer's
//     own configuration already defines is detected from a read-only look at
//     that file and reported, never written through.
//  3. type = "sse" is served as streamable HTTP without a word. A protocol
//     silently swapped under a session is a live failure rather than a missing
//     server, so a declared SSE server bound for Codex is a named error whose
//     remedy is in the message: scope it with agents = ["claude"].
//  4. There is no ${VAR} interpolation anywhere. Everything niwa writes is
//     already resolved, so a surviving "${" is an authoring bug rather than
//     something to hand to an agent -- one of which would expand it and one of
//     which would not.
//
// The existing verbatim .mcp.json file-distribution route is untouched by all
// of this. It stays byte-opaque -- niwa has never parsed it and does not start
// -- and a workspace that uses it without a structured declaration gets one
// honest line at apply time saying where those servers reach.

// mcpFileMode is the permission a generated MCP configuration is written with.
// The declaration's env and headers values resolve through the vault pipeline,
// so a generated file can carry secret material even when a particular
// workspace's does not; the restrictive mode is a property of what the file may
// hold rather than of what one workspace put in it.
const mcpFileMode = 0o600

// generatedConfigMarker is the first line of a configuration document niwa
// generates into a tree it does not own. It is the same ownership mechanism the
// context documents use -- first line identifies the file as niwa's -- spelled
// as a comment so the document it opens still parses as configuration.
const generatedConfigMarker = "# Generated by niwa (niwa-generated-config): every `niwa apply` rewrites this file, so edits made here are lost."

// codexMCPTable is the top-level table Codex reads server definitions from,
// both in the project layer niwa writes and in the developer's own
// configuration the collision check reads.
const codexMCPTable = "mcp_servers"

// claudeMCPFileName is the file a Claude session reads project MCP servers
// from. It is also the destination a workspace names when it distributes one
// verbatim through the file tables, which is how the compatibility report
// recognizes that route.
const claudeMCPFileName = ".mcp.json"

// MCPTransport is how a session reaches a declared server.
type MCPTransport string

const (
	// MCPTransportStdio runs a command and speaks over its pipes.
	MCPTransportStdio MCPTransport = "stdio"

	// MCPTransportHTTP is streamable HTTP against a URL.
	MCPTransportHTTP MCPTransport = "http"

	// MCPTransportSSE is server-sent events against a URL. It is declarable
	// because Claude Code implements it; an agent that does not is required to
	// say so rather than serve something else.
	MCPTransportSSE MCPTransport = "sse"
)

// MCPServer is one declared server with every value already resolved. The
// producer never sees a vault reference or an unresolved mark: internal/workspace
// resolves the declaration first, which is what makes "nothing written relies on
// load-time expansion" a property of the pipeline rather than a hope about the
// generator.
type MCPServer struct {
	// Name is the name a session addresses the server by, and the key both
	// generated formats use.
	Name string

	// Transport is the declared transport, empty when the author left it to be
	// inferred from Command or URL.
	Transport MCPTransport

	// Command is the stdio server's executable.
	Command string

	// Args are the stdio server's arguments.
	Args []string

	// Env is the stdio server's environment, resolved.
	Env map[string]string

	// URL is the http or sse endpoint.
	URL string

	// Headers are the http or sse request headers, resolved.
	Headers map[string]string

	// Agents restricts which agents this server is generated for, by
	// internal/agent's names. Empty means every agent.
	Agents []string
}

// MCPScope names which tree a generated MCP configuration is being produced
// for. Which scope an agent takes is a fact about that agent's discovery, so it
// lives in the layout table below and a caller offers both scopes to every
// producer rather than deciding for one.
//
// The zero value is not a scope, so a caller that forgets to set one gets an
// error rather than a file in whichever place happens to be first.
type MCPScope uint8

const (
	// MCPAtInstanceRoot is the prepared instance's own root, which niwa owns
	// outright.
	MCPAtInstanceRoot MCPScope = iota + 1

	// MCPInRepo is a cloned repository or a worktree of one -- a tree niwa
	// does not own, where a generated file is under the ownership rule.
	MCPInRepo
)

// MCPCollisionSpec says what internal/workspace must read before this agent's
// MCP plan can be produced: the developer's own configuration for that agent,
// and the table their server names live under.
//
// It is the same seam ContextProbeSpec is, for the same reason. Reading a file
// in the developer's home is workspace work; which file, and what a colliding
// name means, is a fact about one agent. A zero spec means this agent's
// generated names cannot collide with anything, so nothing is read at all.
//
// The read is deliberately a direct decode rather than shelling out to the
// agent's own CLI: a listing command fails wholesale on a malformed
// configuration, which is exactly the case where niwa still needs an answer.
type MCPCollisionSpec struct {
	// ConfigDirEnv is the agent's own override naming the directory its
	// configuration lives in, empty when it has none.
	ConfigDirEnv string

	// ConfigDir is that directory relative to the developer's home, used when
	// the override is unset.
	ConfigDir []string

	// ConfigFile is the configuration file inside that directory.
	ConfigFile string

	// Table is the top-level TOML table server names are keyed under.
	Table string
}

// IsZero reports whether the spec asks for nothing.
func (s MCPCollisionSpec) IsZero() bool {
	return s.ConfigFile == "" && s.Table == "" && len(s.ConfigDir) == 0 && s.ConfigDirEnv == ""
}

// MCPInputs is one generated MCP configuration: which tree it goes in, which
// servers the workspace declared, what the developer's own configuration
// already defines, and what a pre-pass found at the path.
type MCPInputs struct {
	// Scope selects which tree this is.
	Scope MCPScope

	// Dir is the absolute root of that tree.
	Dir string

	// Servers are the declared servers, resolved. Order does not matter: the
	// producer sorts them, so the generated bytes are the same on every apply.
	Servers []MCPServer

	// Existing are the server names the developer's own configuration for this
	// agent already defines, read per MCPCollisionSpec. Empty means either that
	// there are none or that the read could not be made -- which the caller
	// reports; a configuration the agent itself cannot load runs no session
	// that could see a merged hybrid, so proceeding is safe on the merits.
	Existing []string

	// Probe is what the caller found at the path this plan would write, per
	// MCPProbeSpec. It is consulted only where the generated file lands in a
	// tree niwa does not own.
	Probe ContextProbe
}

// mcpFormat is the shape of one agent's generated MCP configuration.
type mcpFormat uint8

const (
	// mcpFormatClaudeJSON is Claude Code's .mcp.json document.
	mcpFormatClaudeJSON mcpFormat = iota + 1

	// mcpFormatCodexTOML is Codex's [mcp_servers.<name>] project-layer
	// entries.
	mcpFormatCodexTOML
)

// mcpLayout is where and how one agent's MCP configuration is generated.
type mcpLayout struct {
	// scope is the one tree this agent's configuration is written in.
	scope MCPScope

	// path is the file, as path segments below that tree's root.
	path []string

	// format is the document shape.
	format mcpFormat

	// owned marks a file that lands in a tree niwa does not own, putting it
	// under the ownership rule: written only where the name is free or already
	// carries niwa's marker.
	owned bool

	// unsupported are the transports this agent cannot serve as declared. A
	// declared server on one of them is an error naming the remedy, never a
	// quiet substitution.
	unsupported []MCPTransport

	// collision is what to read before generating, to find a name the
	// developer's own configuration already defines.
	collision MCPCollisionSpec

	// verbatimFileName is the destination the compatibility file-distribution
	// route uses for this agent, empty when the agent has no such route.
	verbatimFileName string
}

// mcpLayouts is the per-agent table.
//
// Claude's document goes at the instance root and nowhere else, which is the
// reach the verbatim route already has: a project .mcp.json under a repository
// would have to be distributed under a .local name that Claude Code does not
// read, and writing it under the plain name would put niwa in a fight with the
// .mcp.json plenty of repositories commit. Codex's goes in each repository and
// nowhere else, for the mirror-image reason: Codex reads a project layer from
// the nearest project root downward, and an instance root is not one, so a
// configuration written there would be bytes no session ever loads.
var mcpLayouts = map[agent.Agent]mcpLayout{
	agent.AgentClaude: {
		scope:            MCPAtInstanceRoot,
		path:             []string{claudeMCPFileName},
		format:           mcpFormatClaudeJSON,
		verbatimFileName: claudeMCPFileName,
	},
	agent.AgentCodex: {
		scope:       MCPInRepo,
		path:        []string{".codex", "config.toml"},
		format:      mcpFormatCodexTOML,
		owned:       true,
		unsupported: []MCPTransport{MCPTransportSSE},
		collision: MCPCollisionSpec{
			ConfigDirEnv: "CODEX_HOME",
			ConfigDir:    []string{".codex"},
			ConfigFile:   "config.toml",
			Table:        codexMCPTable,
		},
	},
}

// mcpLayout returns this producer's agent's layout, and false for an agent that
// takes no generated MCP configuration.
func (p Producer) mcpLayout() (mcpLayout, bool) {
	resolved, err := agent.ParseAgent(string(p.ag))
	if err != nil {
		return mcpLayout{}, false
	}
	layout, ok := mcpLayouts[resolved]
	return layout, ok
}

// mcpPath is the absolute path of the generated configuration inside dir.
func (l mcpLayout) mcpPath(dir string) string {
	return filepath.Join(append([]string{dir}, l.path...)...)
}

// MCPCollisionSpec returns what the caller must read before this agent's MCP
// plan can be produced. The zero spec means nothing.
func (p Producer) MCPCollisionSpec() MCPCollisionSpec {
	layout, ok := p.mcpLayout()
	if !ok {
		return MCPCollisionSpec{}
	}
	return layout.collision
}

// MCPProbeSpec returns what the caller must inspect at scope in dir before
// asking for an MCP plan that writes there. The zero spec means nothing: the
// instance root is niwa's own directory, and a file there is not under the
// ownership rule that governs a file in somebody's repository.
//
// It reuses the context probe's spec and result types rather than declaring a
// second pair of its own. The question is the same one -- is the name niwa
// would write free, or already carrying niwa's marker -- and the workspace-side
// answer is written to a spec, not to a capability.
func (p Producer) MCPProbeSpec(scope MCPScope, dir string) ContextProbeSpec {
	layout, ok := p.mcpLayout()
	if !ok || !layout.owned || layout.scope != scope || dir == "" {
		return ContextProbeSpec{}
	}
	return ContextProbeSpec{
		Dir:         dir,
		OwnedPath:   layout.mcpPath(dir),
		OwnerMarker: generatedConfigMarker,
	}
}

// MCPPlan declares this agent's generated MCP configuration for one tree.
//
// Everything that could make the generated document unusable is decided before
// a single entry exists: an unmappable transport, a value that never resolved,
// a name the developer's own configuration already defines, a document that
// does not decode back to what was intended. Each of those returns an error and
// an empty plan, so the failure mode is a reported apply failure rather than a
// file a session cannot load.
//
// An agent the table does not declare MCP delivery for, a scope this agent does
// not take, and a workspace declaring no servers each produce an empty plan --
// not an error, because "no servers here" is an answer rather than a fault.
func (p Producer) MCPPlan(in MCPInputs) (*Plan, error) {
	ok, err := p.delivers(MCPServers)
	if err != nil {
		return nil, err
	}
	layout, hasLayout := p.mcpLayout()
	if !ok || !hasLayout || in.Dir == "" || layout.scope != in.Scope {
		return &Plan{}, nil
	}

	servers := p.mcpServersForAgent(in.Servers)
	if len(servers) == 0 {
		return &Plan{}, nil
	}

	if err := validateMCPServers(servers, layout); err != nil {
		return nil, err
	}
	if err := checkMCPCollisions(servers, in.Existing, layout); err != nil {
		return nil, err
	}

	content, err := renderMCPDocument(servers, layout)
	if err != nil {
		return nil, err
	}

	path := layout.mcpPath(in.Dir)
	entry := Entry{
		Capability: MCPServers,
		Op:         OpWriteFile,
		Path:       path,
		Content:    content,
		Mode:       mcpFileMode,
		Managed:    true,
	}
	if !layout.owned {
		return &Plan{Entries: []Entry{entry}}, nil
	}

	// A repository that commits its own file at this name keeps it. niwa
	// writes nothing there, says so, and exempts the path from the cleanup
	// that would otherwise delete a recorded path this apply did not produce.
	if in.Probe.Foreign {
		return &Plan{
			Warnings: []string{mcpConflictWarning(in.Probe.OwnedPath)},
			Exempt:   []string{in.Probe.OwnedPath},
		}, nil
	}
	entry.Pre = IfNotForeign
	entry.Owner = generatedConfigMarker
	entry.ExcludeAs = excludePattern(in.Dir, path)
	return &Plan{Entries: []Entry{entry}}, nil
}

// MCPVerbatimReport is the line the apply reports for a workspace that
// distributes an MCP configuration file through the verbatim file-distribution
// route with no structured declaration behind it.
//
// The route keeps working exactly as it did -- niwa has never parsed that file
// and does not start -- but what it delivers reaches one agent's sessions, and
// saying so costs one line. destinations are the file tables' destination
// paths; declared says whether the workspace also declares [mcp.servers]. An
// empty string means there is nothing to report.
func (p Producer) MCPVerbatimReport(destinations []string, declared bool) string {
	layout, ok := p.mcpLayout()
	if !ok || declared || layout.verbatimFileName == "" {
		return ""
	}
	resolved, err := agent.ParseAgent(string(p.ag))
	if err != nil {
		return ""
	}
	for _, dest := range destinations {
		if filepath.Base(filepath.FromSlash(dest)) != layout.verbatimFileName {
			continue
		}
		return fmt.Sprintf(
			"%s is distributed verbatim, so the MCP servers it defines reach %s sessions only; declare them under [mcp.servers.<name>] to have niwa generate every agent's own format from one declaration",
			dest, resolved)
	}
	return ""
}

// mcpServersForAgent returns the servers this producer's agent generates, in
// name order, dropping the ones a declaration scoped to other agents.
func (p Producer) mcpServersForAgent(servers []MCPServer) []MCPServer {
	resolved, err := agent.ParseAgent(string(p.ag))
	if err != nil {
		return nil
	}
	out := make([]MCPServer, 0, len(servers))
	for _, s := range servers {
		if len(s.Agents) > 0 && !slices.Contains(s.Agents, string(resolved)) {
			continue
		}
		out = append(out, s)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// mcpTransport resolves a server's transport: the declared one, or the one its
// shape implies. A declaration that disagrees with the shape is an error rather
// than a precedence rule, because either half could be the typo.
func mcpTransport(s MCPServer) (MCPTransport, error) {
	hasCommand := strings.TrimSpace(s.Command) != ""
	hasURL := strings.TrimSpace(s.URL) != ""

	switch {
	case hasCommand && hasURL:
		return "", fmt.Errorf("mcp server %q declares both command and url; a server is one or the other", s.Name)
	case !hasCommand && !hasURL:
		return "", fmt.Errorf("mcp server %q declares neither command nor url; there is nothing to connect to", s.Name)
	}

	implied := MCPTransportHTTP
	if hasCommand {
		implied = MCPTransportStdio
	}

	switch s.Transport {
	case "":
		return implied, nil
	case MCPTransportStdio:
		if !hasCommand {
			return "", fmt.Errorf("mcp server %q declares transport %q with a url; a stdio server is reached through a command", s.Name, s.Transport)
		}
		return MCPTransportStdio, nil
	case MCPTransportHTTP, MCPTransportSSE:
		if !hasURL {
			return "", fmt.Errorf("mcp server %q declares transport %q with a command; a %s server is reached through a url", s.Name, s.Transport, s.Transport)
		}
		return s.Transport, nil
	default:
		return "", fmt.Errorf("mcp server %q declares unknown transport %q; accepted values are stdio, http, sse", s.Name, s.Transport)
	}
}

// validateMCPServers checks every server against what this agent's format can
// carry, before any of them is rendered.
//
// The cross-transport checks are not defensive tidiness. A Codex configuration
// carrying an http-only field on a stdio entry fails the whole config load --
// every valid server beside it included -- so a field niwa passed through
// "because the agent will ignore what it does not understand" would take a
// developer's whole session with it.
func validateMCPServers(servers []MCPServer, layout mcpLayout) error {
	seen := map[string]bool{}
	for _, s := range servers {
		if strings.TrimSpace(s.Name) == "" {
			return fmt.Errorf("an mcp server is declared with an empty name")
		}
		if seen[s.Name] {
			return fmt.Errorf("mcp server %q is declared more than once", s.Name)
		}
		seen[s.Name] = true

		transport, err := mcpTransport(s)
		if err != nil {
			return err
		}
		if slices.Contains(layout.unsupported, transport) {
			return fmt.Errorf(
				"mcp server %q declares transport %q, which this agent serves as streamable HTTP instead of refusing -- a live protocol swap rather than a missing server; scope the server with agents = [\"claude\"] or move it to transport = \"http\"",
				s.Name, transport)
		}

		switch transport {
		case MCPTransportStdio:
			if len(s.Headers) > 0 {
				return fmt.Errorf("mcp server %q is a stdio server carrying headers; headers belong to an http or sse server", s.Name)
			}
		default:
			if len(s.Args) > 0 {
				return fmt.Errorf("mcp server %q is an %s server carrying args; args belong to a stdio server", s.Name, transport)
			}
			if len(s.Env) > 0 {
				return fmt.Errorf("mcp server %q is an %s server carrying env; an http or sse server passes values through headers", s.Name, transport)
			}
		}

		if err := checkMCPResolved(s); err != nil {
			return err
		}
	}
	return nil
}

// checkMCPResolved rejects a value that still carries interpolation syntax.
//
// niwa writes resolved values only, so a surviving "${" is an authoring bug
// rather than a value to hand over -- and handing it over is worse than
// failing: one agent would expand it and the other would pass the literal
// characters to a server, so the same declaration would mean two different
// things.
func checkMCPResolved(s MCPServer) error {
	fields := []struct {
		field string
		value string
	}{
		{"command", s.Command},
		{"url", s.URL},
	}
	for i, arg := range s.Args {
		fields = append(fields, struct {
			field string
			value string
		}{fmt.Sprintf("args[%d]", i), arg})
	}
	for _, key := range sortedStringKeys(s.Env) {
		fields = append(fields, struct {
			field string
			value string
		}{"env." + key, s.Env[key]})
	}
	for _, key := range sortedStringKeys(s.Headers) {
		fields = append(fields, struct {
			field string
			value string
		}{"headers." + key, s.Headers[key]})
	}

	for _, f := range fields {
		if strings.Contains(f.value, "${") {
			return fmt.Errorf(
				"mcp server %q has %s carrying \"${\" after resolution; niwa writes resolved values only, and an agent that expands nothing would pass those characters through verbatim",
				s.Name, f.field)
		}
	}
	return nil
}

// checkMCPCollisions refuses a generated name the developer's own configuration
// already defines.
//
// The merge this prevents is field-by-field and recursive rather than an
// override: the session would run niwa's command with the developer's args and
// cwd, a server neither of them wrote and neither would recognize. Renaming one
// side is the fix, so the error names both definitions.
func checkMCPCollisions(servers []MCPServer, existing []string, layout mcpLayout) error {
	if layout.collision.IsZero() || len(existing) == 0 {
		return nil
	}
	taken := make(map[string]bool, len(existing))
	for _, name := range existing {
		taken[name] = true
	}
	for _, s := range servers {
		if !taken[s.Name] {
			continue
		}
		return fmt.Errorf(
			"mcp server %q is declared in the workspace configuration and already defined under [%s.%s] in your own %s; the layers merge field by field rather than one overriding the other, so a session would run a server neither definition describes -- rename one of them",
			s.Name, layout.collision.Table, s.Name, layout.collision.ConfigFile)
	}
	return nil
}

// renderMCPDocument turns the validated servers into the bytes for this agent's
// format, and decodes the result back before returning it.
//
// The re-decode is the last check rather than a redundant one: everything above
// validates what niwa intended to write, and this validates what it actually
// produced. It is what makes "a generated file never bricks a session" a
// property of the bytes instead of a property of the code that built them.
func renderMCPDocument(servers []MCPServer, layout mcpLayout) ([]byte, error) {
	switch layout.format {
	case mcpFormatClaudeJSON:
		return renderClaudeMCP(servers)
	case mcpFormatCodexTOML:
		return renderCodexMCP(servers)
	default:
		return nil, fmt.Errorf("agentplan: unknown mcp document format %d", uint8(layout.format))
	}
}

// renderClaudeMCP builds the .mcp.json document: one entry per server under
// "mcpServers", in the shape a hand-written file distributed through the
// verbatim route already has -- command, args, and env for a stdio server; a
// type, url, and headers for the others.
func renderClaudeMCP(servers []MCPServer) ([]byte, error) {
	entries := make(map[string]any, len(servers))
	for _, s := range servers {
		transport, err := mcpTransport(s)
		if err != nil {
			return nil, err
		}
		entry := map[string]any{}
		if transport == MCPTransportStdio {
			// stdio is the default a bare command implies, so it is left
			// unstated exactly as a hand-written file leaves it.
			entry["command"] = s.Command
			if len(s.Args) > 0 {
				entry["args"] = s.Args
			}
			if len(s.Env) > 0 {
				entry["env"] = s.Env
			}
		} else {
			entry["type"] = string(transport)
			entry["url"] = s.URL
			if len(s.Headers) > 0 {
				entry["headers"] = s.Headers
			}
		}
		entries[s.Name] = entry
	}

	data, err := json.MarshalIndent(map[string]any{"mcpServers": entries}, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("agentplan: rendering the mcp document: %w", err)
	}
	data = append(data, '\n')

	var back map[string]any
	if err := json.Unmarshal(data, &back); err != nil {
		return nil, fmt.Errorf("agentplan: the generated mcp document did not decode back: %w", err)
	}
	return data, nil
}

// renderCodexMCP builds the project-layer TOML: the ownership marker, then one
// [mcp_servers.<name>] table per server. The encoder does the quoting and the
// ordering, so a name needing a quoted key cannot land as a differently-shaped
// document than the one this function meant to write.
func renderCodexMCP(servers []MCPServer) ([]byte, error) {
	entries := make(map[string]any, len(servers))
	for _, s := range servers {
		transport, err := mcpTransport(s)
		if err != nil {
			return nil, err
		}
		entry := map[string]any{}
		if transport == MCPTransportStdio {
			entry["command"] = s.Command
			if len(s.Args) > 0 {
				entry["args"] = s.Args
			}
			if len(s.Env) > 0 {
				entry["env"] = stringMapAsAny(s.Env)
			}
		} else {
			// Codex infers the transport from the presence of url and has no
			// key for it. Writing one would be a key the schema does not
			// carry, which is a whole-config failure rather than a no-op.
			entry["url"] = s.URL
			if len(s.Headers) > 0 {
				entry["http_headers"] = stringMapAsAny(s.Headers)
			}
		}
		entries[s.Name] = entry
	}

	var buf bytes.Buffer
	buf.WriteString(generatedConfigMarker)
	buf.WriteString("\n\n")

	enc := toml.NewEncoder(&buf)
	enc.Indent = ""
	if err := enc.Encode(map[string]any{codexMCPTable: entries}); err != nil {
		return nil, fmt.Errorf("agentplan: rendering the mcp document: %w", err)
	}

	if err := checkCodexMCPDocument(buf.Bytes(), servers); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// checkCodexMCPDocument decodes the complete generated document and checks it
// against the measured schema: the servers that were meant to be there and no
// others, exactly one of command and url on each, no field belonging to the
// other transport, and every value the type the schema expects.
//
// It runs over the decoded document rather than over the inputs on purpose.
// What a session loads is these bytes, and the assertion worth making is about
// them.
func checkCodexMCPDocument(data []byte, servers []MCPServer) error {
	var doc map[string]any
	if _, err := toml.Decode(string(data), &doc); err != nil {
		return fmt.Errorf("agentplan: the generated mcp document is not valid TOML: %w", err)
	}

	raw, ok := doc[codexMCPTable]
	if !ok {
		return fmt.Errorf("agentplan: the generated mcp document carries no [%s] table", codexMCPTable)
	}
	table, ok := raw.(map[string]any)
	if !ok {
		return fmt.Errorf("agentplan: the generated mcp document's %s is not a table", codexMCPTable)
	}
	if len(table) != len(servers) {
		return fmt.Errorf("agentplan: the generated mcp document defines %d server(s), want %d", len(table), len(servers))
	}

	for _, s := range servers {
		entry, present := table[s.Name]
		if !present {
			return fmt.Errorf("agentplan: the generated mcp document is missing server %q", s.Name)
		}
		fields, ok := entry.(map[string]any)
		if !ok {
			return fmt.Errorf("agentplan: the generated entry for mcp server %q is not a table", s.Name)
		}

		_, hasCommand := fields["command"]
		_, hasURL := fields["url"]
		if hasCommand == hasURL {
			return fmt.Errorf("agentplan: the generated entry for mcp server %q must carry exactly one of command and url", s.Name)
		}
		if hasCommand {
			if _, wrong := fields["http_headers"]; wrong {
				return fmt.Errorf("agentplan: the generated entry for mcp server %q carries http_headers on a stdio server", s.Name)
			}
		} else {
			if _, wrong := fields["args"]; wrong {
				return fmt.Errorf("agentplan: the generated entry for mcp server %q carries args on a url server", s.Name)
			}
			if _, wrong := fields["env"]; wrong {
				return fmt.Errorf("agentplan: the generated entry for mcp server %q carries env on a url server", s.Name)
			}
		}

		for key, value := range fields {
			switch key {
			case "command", "url":
				if _, isString := value.(string); !isString {
					return fmt.Errorf("agentplan: the generated %s for mcp server %q is not a string", key, s.Name)
				}
			case "args":
				items, isList := value.([]any)
				if !isList {
					return fmt.Errorf("agentplan: the generated args for mcp server %q is not a list", s.Name)
				}
				for i, item := range items {
					if _, isString := item.(string); !isString {
						return fmt.Errorf("agentplan: the generated args[%d] for mcp server %q is not a string", i, s.Name)
					}
				}
			case "env", "http_headers":
				values, isTable := value.(map[string]any)
				if !isTable {
					return fmt.Errorf("agentplan: the generated %s for mcp server %q is not a table", key, s.Name)
				}
				for name, item := range values {
					if _, isString := item.(string); !isString {
						return fmt.Errorf("agentplan: the generated %s.%s for mcp server %q is not a string", key, name, s.Name)
					}
				}
			default:
				return fmt.Errorf("agentplan: the generated entry for mcp server %q carries unknown key %q", s.Name, key)
			}
		}
	}
	return nil
}

// mcpConflictWarning is the line reported for a generated configuration niwa
// refused to write. It names the path for the same reason every other refusal
// does: a quiet skip leaves a user with a session that reaches none of the
// servers they declared and nothing anywhere saying why.
func mcpConflictWarning(path string) string {
	return fmt.Sprintf("%s is occupied by something niwa did not write, so no MCP configuration was generated there; nothing at that path was modified or removed, and a session there reaches only the servers that file already defines", path)
}

// stringMapAsAny widens a resolved value map for the TOML encoder.
func stringMapAsAny(in map[string]string) map[string]any {
	out := make(map[string]any, len(in))
	for key, value := range in {
		out[key] = value
	}
	return out
}

// sortedStringKeys orders a value map so a report about one of its entries is
// the same on every run.
func sortedStringKeys(m map[string]string) []string {
	if len(m) == 0 {
		return nil
	}
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
