package agentplan

import (
	"strings"
	"testing"

	"github.com/tsukumogami/niwa/internal/agent"
)

// TestNoPostureIsWrittenWhenNothingIsDeclared is the first safety property,
// asserted directly rather than inferred from the positive case passing.
//
// The document under test is one a workspace would really get -- servers and an
// environment declared, no posture -- so the assertion is about a file that
// exists and does not carry the keys, not about the empty plan a workspace
// declaring nothing at all produces. niwa must never be the reason a session
// runs with weaker guardrails than the developer chose for themselves, and the
// only way to know that is to look for the keys and not find them.
func TestNoPostureIsWrittenWhenNothingIsDeclared(t *testing.T) {
	doc := decodeCodexPayload(t, PayloadInputs{
		Servers: []MCPServer{stdioServer()},
		Env:     map[string]string{"REGION": "eu-west-1"},
	})

	if _, present := doc[codexApprovalKey]; present {
		t.Errorf("%s was written although the workspace declared no approvals posture: %v", codexApprovalKey, doc)
	}
	if _, present := doc[codexSandboxKey]; present {
		t.Errorf("%s was written although the workspace declared no sandbox posture: %v", codexSandboxKey, doc)
	}

	// And the apply says nothing, because there is nothing to say.
	if report := For(agent.AgentCodex).PostureReport(SessionPosture{}); report != "" {
		t.Errorf("an undeclared posture was reported at apply time: %q", report)
	}
}

// TestDeclaredPostureReachesTheMeasuredKeys is the delivery itself: niwa's
// neutral vocabulary arrives at the two keys Codex reads its posture from, in
// Codex's own spelling.
func TestDeclaredPostureReachesTheMeasuredKeys(t *testing.T) {
	doc := decodeCodexPayload(t, PayloadInputs{
		Posture: SessionPosture{Approvals: "on-request", Sandbox: "workspace-write"},
	})

	if got := doc[codexApprovalKey]; got != "on-request" {
		t.Errorf("%s = %v, want on-request", codexApprovalKey, got)
	}
	if got := doc[codexSandboxKey]; got != "workspace-write" {
		t.Errorf("%s = %v, want workspace-write", codexSandboxKey, got)
	}
}

// TestApprovalsNeverImplyASandbox is the third safety property, and it is the
// one that costs something to keep.
//
// Codex's most complete approval suppression is approval_policy = "never"
// *paired with* sandbox_mode = "danger-full-access", which collapses approvals
// and both the filesystem and network sandboxes into one setting -- an
// asymmetry Claude Code's bypassPermissions does not have. A generator that
// read "this workspace wants fewer prompts" and helpfully supplied the sandbox
// half would switch sandboxing off on the strength of a declaration that never
// mentioned it. So the most relaxed approvals value niwa accepts is declared
// here on its own, and the sandbox key must be absent from the generated bytes.
func TestApprovalsNeverImplyASandbox(t *testing.T) {
	doc := decodeCodexPayload(t, PayloadInputs{
		Posture: SessionPosture{Approvals: "never"},
	})

	if got := doc[codexApprovalKey]; got != "never" {
		t.Errorf("%s = %v, want never", codexApprovalKey, got)
	}
	if got, present := doc[codexSandboxKey]; present {
		t.Errorf("relaxing approvals wrote %s = %v; the sandbox is a separate declaration", codexSandboxKey, got)
	}
}

// TestASandboxNeverImpliesAnApprovalPolicy is the mirror direction. Neither key
// is derived from the other, so the independence has to hold both ways round.
func TestASandboxNeverImpliesAnApprovalPolicy(t *testing.T) {
	doc := decodeCodexPayload(t, PayloadInputs{
		Posture: SessionPosture{Sandbox: "full-access"},
	})

	if got := doc[codexSandboxKey]; got != "danger-full-access" {
		t.Errorf("%s = %v, want danger-full-access", codexSandboxKey, got)
	}
	if got, present := doc[codexApprovalKey]; present {
		t.Errorf("declaring a sandbox wrote %s = %v; approvals are a separate declaration", codexApprovalKey, got)
	}
}

// TestPostureAloneProducesADocument covers the workspace that declares posture
// and nothing else. There are no servers and no environment to hang the write
// on, so a producer that only ever wrote a file for those two would deliver
// nothing here.
func TestPostureAloneProducesADocument(t *testing.T) {
	plan, err := For(agent.AgentCodex).PayloadPlan(PayloadInputs{
		Scope:   PayloadInRepo,
		Dir:     "/repo",
		Posture: SessionPosture{Approvals: "on-failure"},
	})
	if err != nil {
		t.Fatalf("PayloadPlan: %v", err)
	}
	if len(plan.Entries) != 1 {
		t.Fatalf("plan declared %d entries for a declared posture, want 1", len(plan.Entries))
	}
	if got := plan.Entries[0].Capability; got != ApprovalPosture {
		t.Errorf("entry capability = %s, want %s", got, ApprovalPosture)
	}
	if got := plan.Entries[0].Mode; got != payloadFileMode {
		t.Errorf("entry mode = %o, want %o", got, payloadFileMode)
	}
}

// TestUnusablePostureDeclarationsAreRefused covers validation-before-write for
// the posture keys, the same discipline the servers and the environment get.
// One key Codex cannot type-check fails its whole config load, so a value niwa
// does not recognize is an error and no entry rather than a file that takes a
// session down -- and guessing at it would be guessing about how much a
// developer's session is allowed to do.
func TestUnusablePostureDeclarationsAreRefused(t *testing.T) {
	cases := map[string]SessionPosture{
		"an approvals value from no vocabulary": {Approvals: "yolo"},
		"a sandbox value from no vocabulary":    {Sandbox: "wide-open"},
		"Codex's own spelling, not niwa's":      {Sandbox: "danger-full-access"},
		"a good key beside a bad one":           {Approvals: "never", Sandbox: "wide-open"},
	}
	for name, posture := range cases {
		plan, err := For(agent.AgentCodex).PayloadPlan(PayloadInputs{
			Scope:   PayloadInRepo,
			Dir:     "/repo",
			Servers: []MCPServer{stdioServer()},
			Posture: posture,
		})
		if err == nil {
			t.Errorf("%s: the declaration was accepted", name)
			continue
		}
		if plan != nil && len(plan.Entries) != 0 {
			t.Errorf("%s: a refused declaration still declared %d entries", name, len(plan.Entries))
		}
	}
}

// TestPostureIsReportedWhenWritten is the second safety property. A workspace
// that changes what a session asks before it acts is a thing a developer needs
// told, so the line names the key, the value, and -- just as importantly -- the
// key niwa did not write, because the risk this reporting exists against is a
// developer assuming that relaxing one relaxed the other.
func TestPostureIsReportedWhenWritten(t *testing.T) {
	report := For(agent.AgentCodex).PostureReport(SessionPosture{Approvals: "never"})
	if report == "" {
		t.Fatal("a declared posture was written with nothing reported at apply time")
	}
	if !strings.Contains(report, codexApprovalKey) || !strings.Contains(report, `"never"`) {
		t.Errorf("the report does not name the key and value it wrote: %q", report)
	}
	if !strings.Contains(report, codexSandboxKey) {
		t.Errorf("the report does not name the key it left alone: %q", report)
	}

	both := For(agent.AgentCodex).PostureReport(SessionPosture{Approvals: "on-request", Sandbox: "read-only"})
	if !strings.Contains(both, `"on-request"`) || !strings.Contains(both, `"read-only"`) {
		t.Errorf("the report does not name both written values: %q", both)
	}
}

// TestAgentWithNoPostureRouteWritesNoPostureHere keeps the neutral declaration
// out of a document that does not carry it. Claude Code's posture comes from
// its settings document and its own declaration; this payload is servers only,
// and a posture reaching this producer changes nothing about it.
func TestAgentWithNoPostureRouteWritesNoPostureHere(t *testing.T) {
	producer := For(agent.AgentClaude)
	plan, err := producer.PayloadPlan(PayloadInputs{
		Scope:   PayloadAtInstanceRoot,
		Dir:     "/instance",
		Posture: SessionPosture{Approvals: "never", Sandbox: "full-access"},
	})
	if err != nil {
		t.Fatalf("PayloadPlan(claude): %v", err)
	}
	if len(plan.Entries) != 0 {
		t.Errorf("claude's payload declared %d entries for a posture it reads elsewhere", len(plan.Entries))
	}
	if report := producer.PostureReport(SessionPosture{Approvals: "never"}); report != "" {
		t.Errorf("claude's payload reported a posture write it does not perform: %q", report)
	}
}

// TestGeneratedPostureCheckCatchesADamagedOne exercises the last gate directly.
// The check runs over the decoded document, so a document that does not say
// what the producer meant is caught even when every input validated -- and both
// absence arms are exercised, because an unasked-for posture key is the failure
// this whole delivery is written to prevent.
func TestGeneratedPostureCheckCatchesADamagedOne(t *testing.T) {
	declared := SessionPosture{Approvals: "on-request", Sandbox: "read-only"}
	good := map[string]any{
		codexApprovalKey: "on-request",
		codexSandboxKey:  "read-only",
	}
	if err := checkCodexPosture(good, declared); err != nil {
		t.Fatalf("a well-formed posture was rejected: %v", err)
	}
	if err := checkCodexPosture(map[string]any{}, SessionPosture{}); err != nil {
		t.Fatalf("an absent posture was rejected for a workspace that declared none: %v", err)
	}

	damaged := map[string]struct {
		doc      map[string]any
		declared SessionPosture
	}{
		"a key that vanished":            {map[string]any{codexApprovalKey: "on-request"}, declared},
		"a value that did not survive":   {map[string]any{codexApprovalKey: "never", codexSandboxKey: "read-only"}, declared},
		"a value of the wrong type":      {map[string]any{codexApprovalKey: int64(3), codexSandboxKey: "read-only"}, declared},
		"a sandbox nobody declared":      {map[string]any{codexApprovalKey: "never", codexSandboxKey: "danger-full-access"}, SessionPosture{Approvals: "never"}},
		"an approval policy nobody sent": {map[string]any{codexApprovalKey: "never"}, SessionPosture{}},
	}
	for name, tc := range damaged {
		if err := checkCodexPosture(tc.doc, tc.declared); err == nil {
			t.Errorf("%s: the check accepted a document it should not have", name)
		}
	}
}
