package cli

import (
	"bytes"
	"context"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/tsukumogami/niwa/internal/config"
	"github.com/tsukumogami/niwa/internal/github"
	"github.com/tsukumogami/niwa/internal/vault"
	"github.com/tsukumogami/niwa/internal/vault/fake"
	"github.com/tsukumogami/niwa/internal/workspace"
)

// TestAllowMissingSecretsIsADeprecatedNoOp covers the whole contract the
// flag now carries: still accepted, marked deprecated, discoverable in
// help, noisy on use, and refused alongside --strict-secrets.
func TestAllowMissingSecretsIsADeprecatedNoOp(t *testing.T) {
	for _, cmd := range []*cobra.Command{applyCmd, createCmd} {
		t.Run(cmd.Name()+"/registered_and_deprecated", func(t *testing.T) {
			f := cmd.Flags().Lookup(allowMissingSecretsFlag)
			if f == nil {
				t.Fatalf("--%s must stay registered on %s", allowMissingSecretsFlag, cmd.Name())
			}
			if f.Deprecated == "" {
				t.Errorf("--%s must be marked deprecated on %s", allowMissingSecretsFlag, cmd.Name())
			}
			// pflag's MarkDeprecated hides the flag as a side effect.
			// Hiding it would put the notice out of reach of the person
			// still passing the flag, which is the only reader who needs
			// it.
			if f.Hidden {
				t.Errorf("--%s must stay visible in %s help output", allowMissingSecretsFlag, cmd.Name())
			}
		})

		t.Run(cmd.Name()+"/help_carries_the_notice", func(t *testing.T) {
			usages := cmd.Flags().FlagUsages()
			if !strings.Contains(usages, "--"+allowMissingSecretsFlag) {
				t.Fatalf("%s help output omits --%s:\n%s", cmd.Name(), allowMissingSecretsFlag, usages)
			}
			if !strings.Contains(usages, "DEPRECATED") {
				t.Errorf("%s help output omits the deprecation notice:\n%s", cmd.Name(), usages)
			}
		})

		t.Run(cmd.Name()+"/using_it_writes_a_notice_to_stderr", func(t *testing.T) {
			// The commands are package globals and an earlier test may
			// have redirected the root's output; clear it so this test
			// observes the production destination.
			rootCmd.SetOut(nil)
			rootCmd.SetErr(nil)
			cmd.SetOut(nil)
			cmd.SetErr(nil)
			out := captureOSStderr(t, func() {
				resetFlagsAfter(t, cmd, allowMissingSecretsFlag)
				if err := cmd.ParseFlags([]string{"--" + allowMissingSecretsFlag}); err != nil {
					t.Fatalf("ParseFlags: %v", err)
				}
			})
			if !strings.Contains(out, "has been deprecated") {
				t.Errorf("%s: expected a deprecation notice on stderr, got %q", cmd.Name(), out)
			}
		})
	}

	t.Run("rejected_alongside_strict_secrets", func(t *testing.T) {
		// Stub RunE so a failure to reject surfaces as this marker rather
		// than as a real apply against the developer's machine. cobra
		// validates flag groups before RunE, so the rejection path never
		// reaches the stub.
		savedRun := applyCmd.RunE
		applyCmd.RunE = func(*cobra.Command, []string) error {
			return errApplyRanDespiteConflict
		}
		t.Cleanup(func() { applyCmd.RunE = savedRun })
		resetFlagsAfter(t, applyCmd, allowMissingSecretsFlag, strictSecretsFlagName)

		var buf bytes.Buffer
		rootCmd.SetOut(&buf)
		rootCmd.SetErr(&buf)
		t.Cleanup(func() {
			rootCmd.SetOut(nil)
			rootCmd.SetErr(nil)
			rootCmd.SetArgs(nil)
		})
		rootCmd.SetArgs([]string{"apply", "--" + allowMissingSecretsFlag, "--" + strictSecretsFlagName})

		err := rootCmd.Execute()
		if err == nil {
			t.Fatal("expected the contradiction to be rejected, got a successful run")
		}
		if err == errApplyRanDespiteConflict {
			t.Fatal("apply ran with both flags set; the contradiction was resolved silently")
		}
		msg := err.Error()
		if !strings.Contains(msg, allowMissingSecretsFlag) || !strings.Contains(msg, strictSecretsFlagName) {
			t.Errorf("rejection must name both flags, got: %v", err)
		}
	})
}

// errApplyRanDespiteConflict marks the branch the mutual-exclusion test
// must never reach.
var errApplyRanDespiteConflict = errTestSentinel("apply ran")

type errTestSentinel string

func (e errTestSentinel) Error() string { return string(e) }

// TestAllowMissingSecretsChangesNoOutcome runs the provisioning pipeline
// twice per shortfall shape -- once with the flag parsed on the CLI,
// once without -- and requires the error and every generated byte to
// match.
//
// Both shortfall shapes are covered because they used to be handled by
// different code: an absent key came back as ErrKeyNotFound, an
// unreachable provider as ErrProviderUnreachable, and the retired flag
// was documented as acting on both.
func TestAllowMissingSecretsChangesNoOutcome(t *testing.T) {
	shapes := []struct {
		name         string
		providerTOML string
	}{
		{
			// The provider answers, and does not hold the key.
			name:         "absent_key",
			providerTOML: "[vault.provider]\nkind = \"fake\"\n\n[vault.provider.values]\nOTHER_KEY = \"unrelated\"\n",
		},
		{
			// The provider cannot be contacted at all.
			name:         "unreachable_provider",
			providerTOML: "[vault.provider]\nkind = \"fake\"\nfail_open = true\n",
		},
	}

	for _, shape := range shapes {
		t.Run(shape.name, func(t *testing.T) {
			withFakeVaultBackendForCLI(t)
			withoutErr, withoutFiles := provisionWithShortfall(t, shape.providerTOML, false)
			withErr, withFiles := provisionWithShortfall(t, shape.providerTOML, true)

			if withoutErr != withErr {
				t.Errorf("exit outcome differs:\n without: %v\n with:    %v", withoutErr, withErr)
			}
			// Guard against a vacuous pass: if the pipeline stopped before
			// materializing, both sides would be trivially equal.
			envFile := filepath.Join("default", "app", ".local.env")
			if _, ok := withoutFiles[envFile]; !ok {
				t.Fatalf("expected %s to be generated; got %v", envFile, sortedFilePaths(withoutFiles))
			}
			for path, want := range withoutFiles {
				got, ok := withFiles[path]
				if !ok {
					t.Errorf("%s: written without the flag, missing with it", path)
					continue
				}
				if got != want {
					t.Errorf("%s differs:\n without: %q\n with:    %q", path, want, got)
				}
			}
			for path := range withFiles {
				if _, ok := withoutFiles[path]; !ok {
					t.Errorf("%s: written with the flag, missing without it", path)
				}
			}
		})
	}
}

// provisionWithShortfall creates one instance whose declared secret
// cannot be supplied, and returns the pipeline's error text (empty when
// it succeeded) plus every file under the instance root keyed by its
// path relative to that root.
//
// withFlag parses --allow-missing-secrets on the real createCmd before
// the run, so the flag travels the same path a user's invocation would.
// Nothing reads it back: the flag binds to no variable, which is the
// property this test exists to keep true.
func provisionWithShortfall(t *testing.T, providerTOML string, withFlag bool) (string, map[string]string) {
	t.Helper()

	if withFlag {
		resetFlagsAfter(t, createCmd, allowMissingSecretsFlag)
		if err := createCmd.ParseFlags([]string{"--" + allowMissingSecretsFlag}); err != nil {
			t.Fatalf("ParseFlags: %v", err)
		}
	}

	configTOML := `
[workspace]
name = "noop-ws"

[[sources]]
org = "testorg"

[groups.default]
repos = ["app"]

` + providerTOML + `
[env.secrets]
API_TOKEN = "vault://API_TOKEN"
`

	tmpDir := t.TempDir()
	niwaDir := filepath.Join(tmpDir, ".niwa")
	if err := os.MkdirAll(niwaDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(niwaDir, "workspace.toml"), []byte(configTOML), 0o644); err != nil {
		t.Fatal(err)
	}

	result, err := config.Load(filepath.Join(niwaDir, "workspace.toml"))
	if err != nil {
		t.Fatalf("loading workspace config: %v", err)
	}
	cfg := result.Config

	instanceRoot := filepath.Join(tmpDir, cfg.Workspace.Name)
	// Pre-create the repo dir with a .git marker so the Cloner leaves it
	// alone; this test is about materialized content, not cloning.
	if err := os.MkdirAll(filepath.Join(instanceRoot, "default", "app", ".git"), 0o755); err != nil {
		t.Fatal(err)
	}

	applier := workspace.NewApplier(&stubRepoLister{
		repos: map[string][]github.Repo{
			"testorg": {{Name: "app", SSHURL: "git@github.com:testorg/app.git"}},
		},
	})
	applier.Reporter = workspace.NewReporterWithTTY(io.Discard, false)
	applier.Cloner = &workspace.Cloner{}

	var errText string
	if _, createErr := applier.Create(context.Background(), cfg, niwaDir, tmpDir, cfg.Workspace.Name); createErr != nil {
		errText = createErr.Error()
	}

	return errText, readTreeRelative(t, instanceRoot, tmpDir)
}

// sortedFilePaths returns m's keys in order, for a deterministic failure
// message.
func sortedFilePaths(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// stubRepoLister is the github.Client this package's provisioning tests
// need: repo discovery answers from a fixture, never from the network.
type stubRepoLister struct {
	repos map[string][]github.Repo
}

func (s *stubRepoLister) ListRepos(_ context.Context, org string) ([]github.Repo, error) {
	return s.repos[org], nil
}

// withFakeVaultBackendForCLI registers the fake vault backend on
// vault.DefaultRegistry for the duration of the test. The provisioning
// pipeline resolves vault:// URIs through that registry, so this is how
// a CLI-level test gets a provider without a real backend on the host.
func withFakeVaultBackendForCLI(t *testing.T) {
	t.Helper()
	factory := fake.NewFactory()
	if err := vault.DefaultRegistry.Register(factory); err != nil {
		t.Fatalf("registering fake backend: %v", err)
	}
	t.Cleanup(func() {
		if err := vault.DefaultRegistry.Unregister(factory.Kind()); err != nil {
			t.Errorf("unregistering fake backend: %v", err)
		}
	})
}

// readTreeRelative reads every regular file under root into a map keyed
// by path relative to root. Occurrences of tmpDir in file contents are
// replaced with a fixed token, since two runs necessarily live in
// different temp directories and a generated file may name its own
// location.
func readTreeRelative(t *testing.T, root, tmpDir string) map[string]string {
	t.Helper()
	files := map[string]string{}
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		// A symlink (the per-repository Codex payload link, the payload's own
		// skills links) is compared by target: reading one that points at a
		// directory fails, and the target is the generated value anyway.
		if d.Type()&fs.ModeSymlink != 0 {
			target, linkErr := os.Readlink(path)
			if linkErr != nil {
				return linkErr
			}
			files[rel] = "-> " + strings.ReplaceAll(target, tmpDir, "<ROOT>")
			return nil
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		// The state file is the one generated artifact that cannot be
		// compared across runs: it stamps wall-clock times, and it records
		// content hashes of managed files whose text embeds their own
		// absolute path, which necessarily differs between two temp roots.
		// Every file it points at is compared here directly.
		if filepath.ToSlash(rel) == ".niwa/instance.json" {
			return nil
		}
		files[rel] = strings.ReplaceAll(string(data), tmpDir, "<ROOT>")
		return nil
	})
	if err != nil {
		t.Fatalf("reading generated tree: %v", err)
	}
	return files
}

// removedBehaviourClaims are the verbs the retired flag's descriptions
// used to reach for. None of them is true of a no-op, so finding one on
// a line that also names the flag means a description outlived the
// behaviour it describes.
var removedBehaviourClaims = []string{
	"downgrad",
	"overrid",
	"bypass",
	"suppress",
	"empty string",
	"warn",
}

// allowMissingSecretsMention matches both spellings the codebase uses
// for the flag: the command-line name and the Go identifier stem.
var allowMissingSecretsMention = regexp.MustCompile(`(?i)allow[-_]?missing[-_]?secrets`)

// TestAllowMissingSecretsDescriptionsClaimNothingRemoved is the guard
// for the requirement that no description of the flag survives its
// behaviour.
//
// It works in two passes because the two failure modes are different.
// The flag's own help text is read back from the registered flag, so
// that check is exact and cannot be dodged by reformatting. The rest is
// a text scan over units: a Go doc comment is one unit, every other line
// is its own. Comment blocks are joined because that is where a
// description spans lines; Markdown is kept line-scoped because
// neighbouring table rows describe different flags and joining them
// would raise false alarms.
//
// Excluded from the scan:
//
//   - docs/prds and docs/designs, which quote the old behaviour on
//     purpose when recording what changed;
//   - _test.go files, whose comments narrate the change rather than
//     describe the flag to a user, and several of which are pinned
//     against modification.
func TestAllowMissingSecretsDescriptionsClaimNothingRemoved(t *testing.T) {
	t.Run("registered_help_text", func(t *testing.T) {
		for _, cmd := range []*cobra.Command{applyCmd, createCmd} {
			f := cmd.Flags().Lookup(allowMissingSecretsFlag)
			if f == nil {
				t.Fatalf("--%s is not registered on %s", allowMissingSecretsFlag, cmd.Name())
			}
			for _, claim := range removedBehaviourClaims {
				if strings.Contains(strings.ToLower(f.Usage), claim) {
					t.Errorf("%s help text claims %q, which the flag no longer does: %q",
						cmd.Name(), claim, f.Usage)
				}
				if strings.Contains(strings.ToLower(f.Deprecated), claim) {
					t.Errorf("%s deprecation notice claims %q, which the flag no longer does: %q",
						cmd.Name(), claim, f.Deprecated)
				}
			}
		}
	})

	t.Run("repository_scan", func(t *testing.T) {
		root := repoRoot(t)
		err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				if skipScanDir(root, path, d.Name()) {
					return fs.SkipDir
				}
				return nil
			}
			if !scannableFile(d.Name()) {
				return nil
			}
			data, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			rel, _ := filepath.Rel(root, path)
			for _, unit := range scanUnits(string(data), strings.HasSuffix(d.Name(), ".go")) {
				if !allowMissingSecretsMention.MatchString(unit.text) {
					continue
				}
				lower := strings.ToLower(unit.text)
				for _, claim := range removedBehaviourClaims {
					if strings.Contains(lower, claim) {
						t.Errorf("%s:%d describes --%s with %q, which it no longer does:\n\t%s",
							rel, unit.line, allowMissingSecretsFlag, claim, strings.TrimSpace(unit.text))
					}
				}
			}
			return nil
		})
		if err != nil {
			t.Fatalf("scanning repository: %v", err)
		}
	})
}

// scanUnit is one chunk of text the description scan treats as a single
// statement, with the 1-based line where it starts.
type scanUnit struct {
	line int
	text string
}

// scanUnits splits file content into the units the scan compares
// against. In Go source a run of consecutive // lines becomes one unit,
// so a doc comment that names the flag on one line and describes it on
// the next is caught. Everything else is one unit per line.
func scanUnits(content string, isGo bool) []scanUnit {
	var units []scanUnit
	var block []string
	blockStart := 0

	flush := func() {
		if len(block) > 0 {
			units = append(units, scanUnit{line: blockStart, text: strings.Join(block, " ")})
			block = nil
		}
	}

	for i, line := range strings.Split(content, "\n") {
		if isGo && strings.HasPrefix(strings.TrimSpace(line), "//") {
			if len(block) == 0 {
				blockStart = i + 1
			}
			block = append(block, strings.TrimSpace(line))
			continue
		}
		flush()
		units = append(units, scanUnit{line: i + 1, text: line})
	}
	flush()
	return units
}

// skipScanDir reports whether the description scan should descend into
// dir. docs/prds and docs/designs are shipped documents that quote the
// old behaviour when explaining what changed; rewriting them to satisfy
// a scan would falsify the record.
func skipScanDir(root, path, name string) bool {
	if name == ".git" || name == "node_modules" || name == "vendor" {
		return true
	}
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return false
	}
	switch filepath.ToSlash(rel) {
	case "docs/prds", "docs/designs":
		return true
	}
	return false
}

// scannableFile reports whether the description scan reads this file:
// Go source that ships, and Markdown. Test files are out of scope --
// see the note on TestAllowMissingSecretsDescriptionsClaimNothingRemoved.
func scannableFile(name string) bool {
	if strings.HasSuffix(name, "_test.go") {
		return false
	}
	return strings.HasSuffix(name, ".go") || strings.HasSuffix(name, ".md")
}

// repoRoot walks up from the test's working directory to the module
// root, identified by go.mod.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not locate the module root (no go.mod above the test directory)")
		}
		dir = parent
	}
}

// resetFlagsAfter restores the named flags to their defaults, and clears
// their Changed marks, once the test finishes. Commands are package
// globals here, so a parsed flag would otherwise leak into every test
// that runs after it -- including cobra's mutual-exclusion checks, which
// read Changed.
func resetFlagsAfter(t *testing.T, cmd *cobra.Command, names ...string) {
	t.Helper()
	t.Cleanup(func() {
		for _, name := range names {
			f := cmd.Flags().Lookup(name)
			if f == nil {
				continue
			}
			// Value.Set rather than FlagSet.Set: the latter re-prints the
			// deprecation notice, which would pollute the output of any
			// test asserting on it.
			_ = f.Value.Set(f.DefValue)
			f.Changed = false
		}
	})
}

// captureOSStderr runs fn with os.Stderr replaced by a pipe and returns
// what was written. pflag writes the deprecation notice through cobra's
// Print, which resolves to os.Stderr when no output writer is set, so
// the swap is the only way to assert the destination rather than just
// the text.
func captureOSStderr(t *testing.T, fn func()) string {
	t.Helper()
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("pipe: %v", err)
	}
	saved := os.Stderr
	os.Stderr = w
	done := make(chan string, 1)
	go func() {
		var buf bytes.Buffer
		_, _ = io.Copy(&buf, r)
		done <- buf.String()
	}()
	fn()
	os.Stderr = saved
	_ = w.Close()
	out := <-done
	_ = r.Close()
	return out
}
