package envformat

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestMarshalDotenv_ByteCompatibleWithHistorical(t *testing.T) {
	// The historical .local.env serialization: fixed header then KEY=value lines
	// in the given order, no quoting. This pins byte-compatibility (PRD R5).
	kvs := []KV{{Key: "A", Value: "1"}, {Key: "B", Value: "two words"}}
	want := "# Generated by niwa - do not edit manually\nA=1\nB=two words\n"
	got, err := Marshal(FormatDotenv, kvs)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	if string(got) != want {
		t.Errorf("dotenv output:\n got %q\nwant %q", got, want)
	}
}

func TestMarshalJSON_FlatObjectDeterministicOrder(t *testing.T) {
	kvs := []KV{{Key: "Z", Value: "last"}, {Key: "A", Value: "first"}}
	got, err := Marshal(FormatJSON, kvs)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	// Order is preserved as given (Z before A), not sorted by the encoder.
	if idxZ, idxA := strings.Index(string(got), `"Z"`), strings.Index(string(got), `"A"`); idxZ > idxA {
		t.Errorf("expected Z before A (insertion order), got:\n%s", got)
	}
	// It must be valid JSON decoding back to the same map.
	var m map[string]string
	if err := json.Unmarshal(got, &m); err != nil {
		t.Fatalf("output is not valid JSON: %v\n%s", err, got)
	}
	if m["Z"] != "last" || m["A"] != "first" {
		t.Errorf("round-trip mismatch: %v", m)
	}
}

func TestMarshalShell_SingleQuoteEscaping(t *testing.T) {
	kvs := []KV{{Key: "K", Value: "a'b"}}
	got, err := Marshal(FormatShell, kvs)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	want := "export K='a'\\''b'\n"
	if !strings.Contains(string(got), want) {
		t.Errorf("shell escaping:\n got %q\nwant substring %q", got, want)
	}
}

func TestMarshal_RoundTripTrickyValue(t *testing.T) {
	// A value with spaces, a quote, and a newline must survive each format.
	tricky := "a b'c\nd"
	kvs := []KV{{Key: "K", Value: tricky}}

	// dotenv: a newline in a value breaks the line-based format -- this is a
	// pre-existing dotenv limitation, not introduced here, so dotenv is not
	// asserted for the newline case. json and shell must round-trip.

	// json round-trip.
	jb, err := Marshal(FormatJSON, kvs)
	if err != nil {
		t.Fatalf("json Marshal: %v", err)
	}
	var m map[string]string
	if err := json.Unmarshal(jb, &m); err != nil {
		t.Fatalf("json output invalid: %v\n%s", err, jb)
	}
	if m["K"] != tricky {
		t.Errorf("json round-trip: got %q want %q", m["K"], tricky)
	}

	// shell round-trip: single-quote escaping makes any byte literal. Strip the
	// header and the `export K='...'` wrapper (the value itself may contain
	// newlines), then reverse the ' -> '\'' escaping.
	sb := Marshal2(t, FormatShell, kvs)
	inner := strings.TrimPrefix(sb, header)
	inner = strings.TrimSuffix(inner, "\n")
	inner = strings.TrimPrefix(inner, "export K='")
	inner = strings.TrimSuffix(inner, "'")
	if got := strings.ReplaceAll(inner, `'\''`, "'"); got != tricky {
		t.Errorf("shell round-trip: got %q want %q", got, tricky)
	}
}

func TestMarshal_UnknownFormat(t *testing.T) {
	if _, err := Marshal("yaml", []KV{{Key: "A", Value: "1"}}); err == nil {
		t.Fatal("expected error for unknown format, got nil")
	}
}

// Marshal2 is a tiny test helper that fails on error and returns the string.
func Marshal2(t *testing.T, format string, kvs []KV) string {
	t.Helper()
	b, err := Marshal(format, kvs)
	if err != nil {
		t.Fatalf("Marshal(%s): %v", format, err)
	}
	return string(b)
}
