// Package envformat serializes a repo's resolved secret key-value set into one
// of niwa's supported output formats (dotenv, json, shell). It is a leaf
// package (stdlib only) so the workspace materializer can use it without an
// import cycle, mirroring internal/gitexclude.
package envformat

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// KV is one resolved key-value pair. Callers pass an ordered slice; every
// writer preserves that order so output is deterministic across formats.
type KV struct {
	Key   string
	Value string
}

// Format identifiers accepted by Marshal. They match the string values of
// config.OutputFormat; envformat keeps its own copies to stay a leaf package
// with no config dependency.
const (
	FormatDotenv = "dotenv"
	FormatJSON   = "json"
	FormatShell  = "shell"
)

// header is the leading comment both the dotenv and shell formats emit. It is
// byte-identical to the historical .local.env header so a default dotenv target
// reproduces niwa's prior output exactly.
const header = "# Generated by niwa - do not edit manually\n"

// Marshal serializes kvs into the named format. An unknown format is an error.
func Marshal(format string, kvs []KV) ([]byte, error) {
	switch format {
	case FormatDotenv:
		return marshalDotenv(kvs), nil
	case FormatJSON:
		return marshalJSON(kvs)
	case FormatShell:
		return marshalShell(kvs), nil
	default:
		return nil, fmt.Errorf("unknown env output format %q", format)
	}
}

// marshalDotenv reproduces the historical .local.env serialization: the fixed
// header comment followed by KEY=value lines in the given order. dotenv does no
// value quoting, matching prior behavior exactly (byte-compatible default).
func marshalDotenv(kvs []KV) []byte {
	var buf strings.Builder
	buf.WriteString(header)
	for _, kv := range kvs {
		buf.WriteString(kv.Key)
		buf.WriteByte('=')
		buf.WriteString(kv.Value)
		buf.WriteByte('\n')
	}
	return []byte(buf.String())
}

// marshalJSON emits a flat object of the pairs in the given order. It builds the
// object manually (rather than json.Marshal over a map) so key order is
// deterministic; each key and value is escaped with encoding/json so any byte is
// safe.
func marshalJSON(kvs []KV) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("{\n")
	for i, kv := range kvs {
		keyJSON, err := json.Marshal(kv.Key)
		if err != nil {
			return nil, fmt.Errorf("encoding json key: %w", err)
		}
		valJSON, err := json.Marshal(kv.Value)
		if err != nil {
			return nil, fmt.Errorf("encoding json value: %w", err)
		}
		buf.WriteString("  ")
		buf.Write(keyJSON)
		buf.WriteString(": ")
		buf.Write(valJSON)
		if i < len(kvs)-1 {
			buf.WriteByte(',')
		}
		buf.WriteByte('\n')
	}
	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

// marshalShell emits sourceable `export KEY='value'` lines. Values are
// single-quote escaped (' -> '\”) so any byte survives a POSIX `source`.
func marshalShell(kvs []KV) []byte {
	var buf strings.Builder
	buf.WriteString(header)
	for _, kv := range kvs {
		buf.WriteString("export ")
		buf.WriteString(kv.Key)
		buf.WriteString("='")
		buf.WriteString(strings.ReplaceAll(kv.Value, "'", `'\''`))
		buf.WriteString("'\n")
	}
	return []byte(buf.String())
}
