// Package envformat serializes a repo's resolved secret key-value set into one
// of niwa's supported output formats (dotenv, json, shell). It is a leaf
// package (stdlib only) so the workspace materializer can use it without an
// import cycle, mirroring internal/gitexclude.
package envformat

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// KV is one resolved key-value pair. Callers pass an ordered slice; every
// writer preserves that order so output is deterministic across formats.
type KV struct {
	Key   string
	Value string
}

// Format identifiers accepted by Marshal. They match the string values of
// config.OutputFormat; envformat keeps its own copies to stay a leaf package
// with no config dependency.
const (
	FormatDotenv = "dotenv"
	FormatJSON   = "json"
	FormatShell  = "shell"
)

// header is the leading comment both the dotenv and shell formats emit. It is
// byte-identical to the historical .local.env header so a default dotenv target
// reproduces niwa's prior output exactly.
const header = "# Generated by niwa - do not edit manually\n"

// Marshal serializes kvs into the named format. An unknown format is an error.
// It is the assignments-only shorthand for MarshalItems.
func Marshal(format string, kvs []KV) ([]byte, error) {
	items := make([]Item, len(kvs))
	for i, kv := range kvs {
		items[i] = Item{Key: kv.Key, Value: kv.Value}
	}
	return MarshalItems(format, items)
}

// MarshalItems serializes a document that may mix resolved assignments with
// unresolved-key records into the named format. Callers pass the items in the
// order they want them written — the materializer sorts the union by key, so a
// record lands where a reader scanning for that variable is already looking.
func MarshalItems(format string, items []Item) ([]byte, error) {
	switch format {
	case FormatDotenv:
		return marshalDotenv(items), nil
	case FormatJSON:
		return marshalJSON(items)
	case FormatShell:
		return marshalShell(items), nil
	default:
		return nil, fmt.Errorf("unknown env output format %q", format)
	}
}

// marshalDotenv reproduces the historical .local.env serialization: the fixed
// header comment followed by KEY=value lines in the given order. dotenv does no
// value quoting, matching prior behavior exactly (byte-compatible default).
// A record is written as a whole-line comment, which a dotenv reader discards
// before it splits on "=" — so no neighbouring assignment can change by a byte.
func marshalDotenv(items []Item) []byte {
	var buf strings.Builder
	buf.WriteString(header)
	for _, it := range items {
		if it.Record != nil {
			buf.WriteString(recordLine(it.Key, *it.Record))
			buf.WriteByte('\n')
			continue
		}
		buf.WriteString(it.Key)
		buf.WriteByte('=')
		buf.WriteString(it.Value)
		buf.WriteByte('\n')
	}
	return []byte(buf.String())
}

// marshalJSON emits a flat object of the pairs in the given order. It builds the
// object manually (rather than json.Marshal over a map) so key order is
// deterministic; each key and value is escaped with encoding/json so any byte is
// safe.
//
// JSON has no comment form, so a record becomes a string-valued member whose
// name carries the record prefix and the key. It must stay string-valued: the
// document is flat by contract and a nested object here would break every
// consumer that decodes it as map[string]string. The member is not recoverable
// by niwa's reader, which is dotenv-only; that is accepted, and the record
// exists here for the person reading the file.
func marshalJSON(items []Item) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("{\n")
	for i, it := range items {
		name, value := it.Key, it.Value
		if it.Record != nil {
			name = RecordPrefix + " " + it.Key
			value = recordJSONValue(*it.Record)
		}
		keyJSON, err := json.Marshal(name)
		if err != nil {
			return nil, fmt.Errorf("encoding json key: %w", err)
		}
		valJSON, err := json.Marshal(value)
		if err != nil {
			return nil, fmt.Errorf("encoding json value: %w", err)
		}
		buf.WriteString("  ")
		buf.Write(keyJSON)
		buf.WriteString(": ")
		buf.Write(valJSON)
		if i < len(items)-1 {
			buf.WriteByte(',')
		}
		buf.WriteByte('\n')
	}
	buf.WriteString("}\n")
	return buf.Bytes(), nil
}

// recordJSONValue renders a record's fields as the value half of its JSON
// member. encoding/json escapes the result again on the way out, so the
// description's own encoding survives as literal text a reader can see.
func recordJSONValue(r Record) string {
	return token(r.Level, levelUnspecified) + " " +
		token(r.Cause, causeUnknown) + " " +
		encodeString(r.Description)
}

// marshalShell emits sourceable `export KEY='value'` lines. Values are
// single-quote escaped (' -> '\”) so any byte survives a POSIX `source`.
// A record is a whole-line comment, so the file stays sourceable: the record
// contains no line break, so nothing after the '#' can become a command.
func marshalShell(items []Item) []byte {
	var buf strings.Builder
	buf.WriteString(header)
	for _, it := range items {
		if it.Record != nil {
			buf.WriteString(recordLine(it.Key, *it.Record))
			buf.WriteByte('\n')
			continue
		}
		buf.WriteString("export ")
		buf.WriteString(it.Key)
		buf.WriteString("='")
		buf.WriteString(strings.ReplaceAll(it.Value, "'", `'\''`))
		buf.WriteString("'\n")
	}
	return []byte(buf.String())
}
