package envformat

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// hostileInputs are the author-supplied shapes a record has to survive. Both
// the key and the description reach a record straight out of a TOML file, and
// nothing between the decoder and the writer constrains either.
var hostileInputs = []struct {
	name string
	text string
}{
	{"newline then assignment", "oops\nPATH=/tmp/evil"},
	{"carriage return", "oops\rPATH=/tmp/evil"},
	{"bare equals", "KEY=value"},
	{"record prefix", RecordPrefix + " OTHER required key-not-found \"x\""},
	{"double quote", `he said "hi"`},
	{"backslash", `C:\path\to`},
	{"unicode line separator", "before\u2028PATH=/tmp/evil"},
	{"paragraph separator", "before\u2029after"},
	{"invalid utf8", "bad\xff\xfebytes"},
	{"nul byte", "a\x00b"},
	{"shell metacharacters", "'; rm -rf /; echo '"},
	{"long", strings.Repeat("x", 4096)},
}

// TestRecordIsAlwaysOnePhysicalLine is the security invariant, asserted over
// the WHOLE record rather than only its description. A record that broke across
// two lines would make the second line a real assignment in dotenv and an
// executed command in shell.
func TestRecordIsAlwaysOnePhysicalLine(t *testing.T) {
	for _, in := range hostileInputs {
		t.Run(in.name, func(t *testing.T) {
			// Once as the description, once as the key: both are author-supplied.
			for _, item := range []Item{
				{Key: "GOOD_KEY", Record: &Record{Level: "required", Cause: "key-not-found", Description: in.text}},
				{Key: in.text, Record: &Record{Level: "required", Cause: "key-not-found", Description: "fine"}},
			} {
				line := recordLine(item.Key, *item.Record)
				if strings.ContainsAny(line, "\n\r") {
					t.Errorf("record broke across lines: %q", line)
				}
				for _, sep := range []string{"\u2028", "\u2029"} {
					if strings.Contains(line, sep) {
						t.Errorf("record carries a unicode line separator: %q", line)
					}
				}
			}
		})
	}
}

// TestMarshalDotenvRecordShape pins the rendered form the design chose, so a
// change to it is a deliberate one.
func TestMarshalDotenvRecordShape(t *testing.T) {
	data, err := MarshalItems(FormatDotenv, []Item{
		{Key: "ANTHROPIC_API_KEY", Record: &Record{
			Level:       "required",
			Cause:       "provider-unreachable",
			Description: "API key for Claude Code sessions",
		}},
		{Key: "NIWA_PROFILE", Value: "dev"},
	})
	if err != nil {
		t.Fatalf("MarshalItems: %v", err)
	}
	want := "# Generated by niwa - do not edit manually\n" +
		"# niwa: unresolved ANTHROPIC_API_KEY required provider-unreachable \"API key for Claude Code sessions\"\n" +
		"NIWA_PROFILE=dev\n"
	if string(data) != want {
		t.Errorf("dotenv output =\n%s\nwant\n%s", data, want)
	}
}

// TestMarshalPreservesCallerOrder pins that records interleave wherever the
// caller put them; the materializer is what sorts the union by key.
func TestMarshalPreservesCallerOrder(t *testing.T) {
	items := []Item{
		{Key: "AAA", Value: "1"},
		{Key: "BBB", Record: &Record{Level: "optional", Cause: "no-source"}},
		{Key: "CCC", Value: "3"},
	}
	data, err := MarshalItems(FormatDotenv, items)
	if err != nil {
		t.Fatalf("MarshalItems: %v", err)
	}
	lines := strings.Split(strings.TrimSuffix(string(data), "\n"), "\n")
	if len(lines) != 4 {
		t.Fatalf("expected header + 3 items, got %d lines:\n%s", len(lines), data)
	}
	if lines[1] != "AAA=1" || !strings.HasPrefix(lines[2], RecordPrefix+" BBB") || lines[3] != "CCC=3" {
		t.Errorf("order not preserved:\n%s", data)
	}
}

// TestMarshalJSONStaysValidWithRecords covers the json target: the document has
// to stay decodable, and stay FLAT and string-valued, because that is what its
// consumers assume.
func TestMarshalJSONStaysValidWithRecords(t *testing.T) {
	for _, in := range hostileInputs {
		t.Run(in.name, func(t *testing.T) {
			data, err := MarshalItems(FormatJSON, []Item{
				{Key: "REAL", Value: "value"},
				{Key: in.text, Record: &Record{Level: "required", Cause: "provider-unreachable", Description: in.text}},
				{Key: "ZLAST", Value: "z"},
			})
			if err != nil {
				t.Fatalf("MarshalItems: %v", err)
			}
			var doc map[string]string
			if err := json.Unmarshal(data, &doc); err != nil {
				t.Fatalf("json output is not a valid flat string map: %v\n%s", err, data)
			}
			if doc["REAL"] != "value" || doc["ZLAST"] != "z" {
				t.Errorf("record disturbed a neighbouring member: %v", doc)
			}
			if _, ok := doc[in.text]; ok {
				t.Errorf("record must not appear as a plain assignment for the key")
			}
		})
	}
}

// TestMarshalShellStaysSourceable actually sources the generated file. A record
// is a comment, so the assignments around it must survive unchanged and the
// record itself must execute nothing.
func TestMarshalShellStaysSourceable(t *testing.T) {
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("sh not available")
	}
	data, err := MarshalItems(FormatShell, []Item{
		{Key: "BEFORE", Value: "b"},
		{Key: "OMITTED", Record: &Record{
			Level:       "required",
			Cause:       "provider-unreachable",
			Description: "oops\nexport PWNED=1\n#",
		}},
		{Key: "AFTER", Value: "a'quote"},
	})
	if err != nil {
		t.Fatalf("MarshalItems: %v", err)
	}
	path := filepath.Join(t.TempDir(), "env.sh")
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatal(err)
	}
	out, err := exec.Command(sh, "-c", ". "+path+`; printf '%s|%s|%s' "$BEFORE" "$AFTER" "$PWNED"`).CombinedOutput()
	if err != nil {
		t.Fatalf("sourcing generated shell file failed: %v\n%s\nfile:\n%s", err, out, data)
	}
	if got := string(out); got != "b|a'quote|" {
		t.Errorf("sourced values = %q, want %q (file:\n%s)", got, "b|a'quote|", data)
	}
}

// TestParseRecordRoundTrip covers the reader half: a record this package wrote
// comes back with its key and description intact.
func TestParseRecordRoundTrip(t *testing.T) {
	line := recordLine("ANTHROPIC_API_KEY", Record{
		Level:       "recommended",
		Cause:       "client-not-installed",
		Description: `a "quoted" \ description`,
	})
	key, rec, ok := ParseRecord(line)
	if !ok {
		t.Fatalf("ParseRecord rejected its own output: %q", line)
	}
	if key != "ANTHROPIC_API_KEY" {
		t.Errorf("key = %q", key)
	}
	if rec.Level != "recommended" || rec.Cause != "client-not-installed" {
		t.Errorf("rec = %+v", rec)
	}
	if rec.Description != `a "quoted" \ description` {
		t.Errorf("description = %q", rec.Description)
	}
}

// TestParseRecordUnspecifiedLevelRoundTrips: a key in no requirement sub-table
// has no level, and the record needs a placeholder so the columns do not shift.
// The placeholder must not come back as a level.
func TestParseRecordUnspecifiedLevelRoundTrips(t *testing.T) {
	line := recordLine("KEY", Record{Cause: "no-source"})
	if !strings.Contains(line, " unspecified no-source ") {
		t.Errorf("missing level placeholder: %q", line)
	}
	_, rec, ok := ParseRecord(line)
	if !ok {
		t.Fatalf("ParseRecord rejected %q", line)
	}
	if rec.Level != "" {
		t.Errorf("level = %q, want empty", rec.Level)
	}
}

// TestParseRecordRejectsUntrustedShapes: a record read back is untrusted input,
// because a repository can write its own environment file. Anything that does
// not revalidate is dropped rather than repaired.
func TestParseRecordRejectsUntrustedShapes(t *testing.T) {
	cases := []struct {
		name string
		line string
	}{
		{"not a record", "# just a comment"},
		{"prefix only", RecordPrefix},
		{"too few fields", RecordPrefix + " KEY required key-not-found"},
		{"key with equals", RecordPrefix + ` A=B required key-not-found ""`},
		{"key with dash", RecordPrefix + ` A-B required key-not-found ""`},
		{"encoded key", RecordPrefix + ` "A\nB" required key-not-found ""`},
		{"unencoded description", RecordPrefix + " KEY required key-not-found bare"},
		{"description not a string", RecordPrefix + " KEY required key-not-found 42"},
		{"unterminated description", RecordPrefix + ` KEY required key-not-found "open`},
		{"level with space", RecordPrefix + " KEY  required key-not-found \"\""},
		{"uppercase cause", RecordPrefix + ` KEY required KEY_NOT_FOUND ""`},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if _, _, ok := ParseRecord(c.line); ok {
				t.Errorf("ParseRecord accepted %q", c.line)
			}
		})
	}
}

// TestParseRecordSanitizesDescription: a recovered description flows on into a
// report that reaches a terminal and an agent's context window, so control
// characters are stripped at the boundary.
func TestParseRecordSanitizesDescription(t *testing.T) {
	encoded, err := json.Marshal("a\nb\x1b[31m\u2028c")
	if err != nil {
		t.Fatal(err)
	}
	_, rec, ok := ParseRecord(RecordPrefix + " KEY required key-not-found " + string(encoded))
	if !ok {
		t.Fatal("ParseRecord rejected a well-formed record")
	}
	if rec.Description != "ab[31mc" {
		t.Errorf("description = %q, want control characters stripped", rec.Description)
	}
}

// TestEncodedKeyIsNotRecoverable: the writer encodes a key that fails the
// conservative pattern rather than interpolating it, and the reader rejects the
// encoded form. Fail-closed is the right direction — a dropped record leaves
// the promote path on its hard-error branch.
func TestEncodedKeyIsNotRecoverable(t *testing.T) {
	line := recordLine("bad key\nPATH=/tmp/evil", Record{Level: "required", Cause: "no-source"})
	if strings.Contains(line, "PATH=/tmp/evil\n") {
		t.Fatalf("key was interpolated raw: %q", line)
	}
	if _, _, ok := ParseRecord(line); ok {
		t.Errorf("an encoded key must not revalidate: %q", line)
	}
}

// TestMarshalWithoutRecordsIsByteIdentical: the assignments-only path must not
// have shifted a byte, since the default dotenv target is contractually
// byte-compatible with niwa's historical .local.env.
func TestMarshalWithoutRecordsIsByteIdentical(t *testing.T) {
	kvs := []KV{{Key: "A", Value: "1"}, {Key: "B", Value: "2"}}
	for _, format := range []string{FormatDotenv, FormatJSON, FormatShell} {
		got, err := Marshal(format, kvs)
		if err != nil {
			t.Fatalf("%s: %v", format, err)
		}
		items := []Item{{Key: "A", Value: "1"}, {Key: "B", Value: "2"}}
		want, err := MarshalItems(format, items)
		if err != nil {
			t.Fatalf("%s: %v", format, err)
		}
		if string(got) != string(want) {
			t.Errorf("%s: Marshal and MarshalItems disagree:\n%s\n%s", format, got, want)
		}
	}
}
